//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabaseAutomation.Automation.BaseLogica.XsdAuto.TaxJournalAuto {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TaxJournalAuto {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int idDeloField;
        
        private bool idDeloFieldSpecified;
        
        private string innField;
        
        private string kppField;
        
        private string nameFaceField;
        
        private string fidField;
        
        private System.DateTime dateIzveshenieField;
        
        private bool dateIzveshenieFieldSpecified;
        
        private bool isTksField;
        
        private bool isTksFieldSpecified;
        
        private bool isMailField;
        
        private bool isMailFieldSpecified;
        
        private bool isLk3Field;
        
        private bool isLk3FieldSpecified;
        
        private string typeDocumentField;
        
        private string messageInfoField;
        
        private string extensionsField;
        
        private byte[] documentField;
        
        private bool isPrintField;
        
        private bool isPrintFieldSpecified;
        
        private System.DateTime dataCreateField;
        
        private bool dataCreateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdDelo {
            get {
                return this.idDeloField;
            }
            set {
                this.idDeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdDeloSpecified {
            get {
                return this.idDeloFieldSpecified;
            }
            set {
                this.idDeloFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFace {
            get {
                return this.nameFaceField;
            }
            set {
                this.nameFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateIzveshenie {
            get {
                return this.dateIzveshenieField;
            }
            set {
                this.dateIzveshenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateIzveshenieSpecified {
            get {
                return this.dateIzveshenieFieldSpecified;
            }
            set {
                this.dateIzveshenieFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isTks {
            get {
                return this.isTksField;
            }
            set {
                this.isTksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTksSpecified {
            get {
                return this.isTksFieldSpecified;
            }
            set {
                this.isTksFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isMail {
            get {
                return this.isMailField;
            }
            set {
                this.isMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isMailSpecified {
            get {
                return this.isMailFieldSpecified;
            }
            set {
                this.isMailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isLk3 {
            get {
                return this.isLk3Field;
            }
            set {
                this.isLk3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isLk3Specified {
            get {
                return this.isLk3FieldSpecified;
            }
            set {
                this.isLk3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeDocument {
            get {
                return this.typeDocumentField;
            }
            set {
                this.typeDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPrint {
            get {
                return this.isPrintField;
            }
            set {
                this.isPrintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPrintSpecified {
            get {
                return this.isPrintFieldSpecified;
            }
            set {
                this.isPrintFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DataCreate {
            get {
                return this.dataCreateField;
            }
            set {
                this.dataCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataCreateSpecified {
            get {
                return this.dataCreateFieldSpecified;
            }
            set {
                this.dataCreateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TaxJournalView {
        
        private TaxJournalAuto[] taxJournalAutoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxJournalAuto")]
        public TaxJournalAuto[] TaxJournalAuto {
            get {
                return this.taxJournalAutoField;
            }
            set {
                this.taxJournalAutoField = value;
            }
        }
    }
}
