// Copyright 2014-2018 VintaSoft Ltd. All rights reserved.
// This software is protected by International copyright laws.
// Any copying, duplication, deployment, redistribution, modification or other
// disposition hereof is STRICTLY PROHIBITED without an express written license
// granted by VintaSoft Ltd. This notice may not be removed or otherwise
// altered under any circumstances.
// This code may NOT be used apart of the VintaSoft product.
var Vintasoft;
(function(x){if(void 0==window.jQuery)throw Error("jQuery is not found.");if(void 0==x.version)x.version="1.3.0.1";else if("1.3.0.1"!==x.version)throw Error("Wrong script version.");x.Shared=x.Shared||(x.Shared={});(function(m){function x(a){function b(){}b.prototype=a;return new b}Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var d;if(null==this)throw new TypeError('"this" is null or not defined');var k=
Object(this),g=k.length>>>0;if(0===g)return-1;d=+b||0;Infinity===Math.abs(d)&&(d=0);if(d>=g)return-1;for(d=Math.max(0<=d?d:g-Math.abs(d),0);d<g;){if(d in k&&k[d]===a)return d;d++}return-1});m.extend=function(a,b){a.prototype=x(b.prototype);a.prototype.constructor=a;a.superclass=b.prototype};var b=function(){};b.te=function(a){throw Error(a);};b.tae=function(){b.te("Argument type exception.")};b.toe=function(){b.te("Argument out of range exception.")};b.tne=function(){b.te("Not implemented exception.")};
b.n=function(){for(var a=0;a<arguments.length;a++){var f=arguments[a];("number"!==typeof f||isNaN(f))&&b.tae()}};b.b=function(){for(var a=0;a<arguments.length;a++)"boolean"!==typeof arguments[a]&&b.tae()};b.d=function(a){b.ic(a,Date)||(a=Date.parse(a),isNaN(a)&&b.tae(),a=new Date(a));return a};b.s=function(){for(var a=0;a<arguments.length;a++)"string"!==typeof arguments[a]&&b.tae()};b.sz=function(){for(var a=0;a<arguments.length;a++){var f=arguments[a];b.n(f.width);b.n(f.height)}};b.p=function(){for(var a=
0;a<arguments.length;a++){var f=arguments[a];b.n(f.x);b.n(f.y)}};b.r=function(){for(var a=0;a<arguments.length;a++){var f=arguments[a];b.p(f);b.sz(f)}};b.e=function(a,f){var d=b.ic(a,D)?a.valueOf():a;return new f(d)};b.ic=function(a,b){return a instanceof b};b.c=function(a,f,d){b.ic(a,f)||(void 0!=d?b.te(d):b.tae())};b.ad=function(a,f){Array.isArray(a)||b.tae();for(var d=0;d<a.length;d++)f(a[d])};b.ac=function(a,f){b.ad(a,function(a){b.c(a,f)})};b.isf=function(a){return"function"===typeof a};b.f=
function(a,f){b.isf(a)||(void 0!=f?b.te(f):b.tae())};var D=function(){var a=D.prototype;a.getAllAvailableNames=function(){};a.getAllAvailableValues=function(){};a.valueOf=function(){};a.toString=function(){};a.equals=function(a){};a.isFlagged=function(){return!1}},F=function(){var a=F.prototype;a.toArray=function(){};a.contains=function(a){};a.add=function(a){};a.remove=function(a){};a.isFlagged=function(){return!0}};m.extend(F,D);var C=function(){};C.create=function(a,f){function d(c,a){var l=[];
if(void 0!=h[a])l.push(h[a]);else for(var b=1;b<=e;)0!==g(a,b)&&l.push(h[b]),b*=2;return l.join("|")}function k(c){return{low:c%4294967296|0,high:c/4294967296|0}}function g(c,e){var a=k(c),b=k(e);return 4294967296*(a.high&b.high)+((a.low&b.low)>>>0)}for(var h={},e=0,c=0;c<a.length;c++){var l=a[c].value,L=a[c].name;h[L]=l;h[l]=L}Object.freeze&&Object.freeze(h);if(f)for(c in h)isNaN(Number(c))||(l=parseInt(c),0!==l&&0===g(l,l-1)&&(e+=l));else for(c in h)isNaN(Number(c))||(l=parseInt(c),l>e&&(e=l));
var u=function(c){if("string"===typeof c){var a=Number(c);if(isNaN(a))if(void 0==h[c]){a=0;c=c.split("|");for(var l=0;l<c.length;l++)a+=h[c[l]];c=a}else c=h[c];else c=a}c>e&&b.tae();a=h[c];void 0==a&&f&&(a=d(this,c));void 0!=a&&""!==a||b.tae();this[this[a]=c+0]=a};f?m.extend(u,F):m.extend(u,D);c=u.prototype;c.getAllAvailableNames=function(){var c=[],e;for(e in h)isNaN(Number(e))&&c.push(e);return c};c.getAllAvailableValues=function(){var c=[],e;for(e in h)isNaN(Number(e))&&void 0!=h[e]&&c.push(h[e]);
return c};c.valueOf=function(){for(var c in this){var e=Number(c);if(!isNaN(e))return e}};c.toString=function(){return d(this,this.valueOf())};f&&(c.toArray=function(){var c=this.valueOf(),a=[];if(0===c&&void 0!==h[c])a.push(new u(0));else for(var b=1;b<=e;){if(0!==g(c,b))try{a.push(new u(b))}catch(l){}b*=2}return a},c.contains=function(c){var e=this.valueOf();"string"===typeof c&&(c=h[c]);return g(e,c)===c+0},c.add=function(c){var e=this.valueOf();"string"===typeof c&&(c=h[c]);e=k(e);c=k(c);return new u(4294967296*
(e.high|c.high)+((e.low|c.low)>>>0))},c.remove=function(c){var e=this.valueOf();"string"===typeof c&&(c=h[c]);var a=c;c=k(e);a=k(a);return new u(g(4294967296*(c.high^a.high)+((c.low^a.low)>>>0),e))});c.equals=function(c){var e=this.valueOf();"string"===typeof c&&(c=h[c]);return e===c+0};c.isFlagged=function(){return f};return u};m.WebPixelFormatEnumJS=C.create([{name:"Undefined",value:0},{name:"Indexed1",value:1},{name:"BlackWhite",value:2},{name:"Indexed4",value:4},{name:"Indexed8",value:8},{name:"Gray8",
value:9},{name:"Bgr555",value:14},{name:"Bgr565",value:15},{name:"Gray16",value:16},{name:"Bgr24",value:24},{name:"Bgr32",value:32},{name:"Bgra32",value:33},{name:"Bgr48",value:48},{name:"Bgra64",value:64}],!1);m.WebInterpolationModeEnumJS=C.create([{name:"Default",value:0},{name:"Low",value:1},{name:"High",value:2},{name:"Bilinear",value:3},{name:"Bicubic",value:4},{name:"NearestNeighbor",value:5},{name:"HighQualityBilinear",value:6},{name:"HighQualityBicubic",value:7}],!1);m.WebSmoothingModeEnumJS=
C.create([{name:"Default",value:0},{name:"HighSpeed",value:1},{name:"HighQuality",value:2},{name:"None",value:3},{name:"AntiAlias",value:4}],!1);m.WebImageTypeEnumJS=C.create([{name:"Url",value:1},{name:"Base64",value:2}],!1);var q=function(){};q._301=function(){};q._301=void 0;q.get_SessionId=function(){return q._301};q.set_SessionId=function(a){void 0!=q._301&&b.te("Session ID already initialized.");/^\w+$/.test(a)||b.te("Unsupported Session ID format: ID can contain only latin letters, numbers and '_' symbol.");
q._301=a};q.get_ScrollSize=function(){var a=$("<div>").appendTo(document.body);a.css({overflow:"scroll",visibility:"hidden",position:"absolute",width:"100px",height:"100px"});var b=a[0],d=b.offsetWidth-b.clientWidth;0>d&&(d=100-b.clientWidth);a.remove();return d};q.getScreenDpi=function(){var a=$("<div>").appendTo(document.body);$(a).css({position:"absolute",top:"-100%",left:"-100%",width:"1in",height:"1in"});var b=a[0],b={dpiX:b.offsetWidth,dpiY:b.offsetHeight};a.remove();return b};q.guid=function(){function a(){return Math.floor(65536*
(1+Math.random())).toString(16).substring(1)}return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()};var A=function(a,b,d,k,g){var h=A.prototype;h.get_ShortName=function(){return this._376};h.get_FullName=function(){return this._306};h.get_Value=function(){return this._3};h.get_ReadOnly=function(){return this._419};h.get_Items=function(){return this._75};h.get_RefreshFromParent=function(){return this._95};this._376=a;this._306=b;this._3=d;this._419=k;this._75=[];this._95=g?g:!1},J=function(a,f,d){function k(c,
e){c._3=e._3;c._306=e._306;c._376=e._376;c._419=e._419;c._95=e._95;for(var a=0;a<c._75.length;a++)k(c._75[a],e._75[a])}function g(c,e){for(;c._75.length>e._75.length;)c._75.splice(c._75.length-1,1);for(;c._75.length<e._75.length;)c._75[c._75.length]=e._75[c._75.length];for(var a=0;a<c._75.length;a++)g(c._75[a],e._75[a])}function h(c,e,a){if(c["set_"+e])return c["set_"+e](a),c["get_"+e]();c[e]=a;return c[e]}function e(c,a,l){if("object"===typeof a){var h=[],p;for(p in a)h.push(p);h.sort();for(p=0;p<
h.length;p++){var d=h[p],k="";if(0===d.lastIndexOf("get_",0)&&b.isf(a[d])){var k=d.split("_")[1],f=!0;void 0!=a["set_"+k]&&b.isf(a["set_"+k])&&(f=!1);var g;try{g=a[d]()}catch(m){g=void 0}if(void 0!=g)if("object"!=typeof g){var n=""!==l?l+"_"+k:k,k=new A(k,n,g,f);c.get_Items().push(k)}else n=""!==l?l+"_"+k:k,k=new A(k,n,g,f),c.get_Items().push(k),e(k,g,n)}}if(0===c._75.length&&"object"===typeof a){p=!0;for(d in a)if(b.isf(a[d])){p=!1;break}d=Object.getOwnPropertyNames(a);g=Array.isArray(a);if(p&&!g)for(p=
0;p<d.length;p++)"_"!==d[p][0]&&(n=""!==l?l+"_"+d[p]:d[p],g=a[d[p]],void 0!=g&&("object"!=typeof g?(k=new A(d[p],n,g,!1,!0),c.get_Items().push(k)):(k=new A(d[p],n,g,!1,!0),c.get_Items().push(k),e(k,g,n))));else if(g)for(l=c.get_FullName(),f=!1,p=0;p<a.length;p++)k=new A(""+p,l+"_"+p,a[p],f,!0),c.get_Items().push(k),e(k,a[p],l+"_"+p)}}}function c(e,a,l,h){var k=a.get_Items();if(k.length!==h._75.length)l.push({property:h,value:a._3,updateMarkup:!0});else{for(var d=!1,f=0;f<k.length;f++){a=k[f];var g=
h._75[f];if(a._306!==g._306){l.push({property:h,value:a._3,updateMarkup:!0});d=!0;break}}if(!d)for(f=0;f<k.length;f++)if(a=k[f],g=h._75[f],a._306!==g._306)l.push({property:g,value:g._3,updateMarkup:!0});else if(g._75.length!==a._75.length)l.push({property:g,value:g._3,updateMarkup:!0});else if(0!=a._75.length)c(e,a,l,g);else if(d=g._3,a._3!=d){g=!0;if(b.ic(a._3,Array)&&b.ic(d,Array))if(a._3.length!=d.length)g=!1;else for(var m=0;m<a._3.length;m++){if(a._3[m]!=d[m]){g=!1;break}}else g=!1;g||l.push({property:a,
value:d})}}}var l=J.prototype;l.get_ObjectProperties=function(){return this._159};l.setPropertyValue=function(c,e){for(var a=this._212,l=c.split("_"),b=this._159,k=-1,d=0;d<l.length;d++)for(var g=0;g<b._75.length;g++)if(b._75[g]._376===l[d]){b=b._75[g];-1==k||b._95||(k=-1);-1==k&&b._95&&(k=Math.max(d-1,0));break}var f;if(void 0!=b){g=[];switch(typeof b._3){case "boolean":e="True"===e?!0:!1;break;case "number":e=parseFloat(e)}try{if(1==l.length){var m=l[0];h(a,m,e)}else if(b._95){v=a;for(a=0;a<k;a++)v=
Array.isArray(v)&&!isNaN(Number(l[a]))?v[Number(l[a])]:v["get_"+l[a]]();for(var n=l[k],q=v["get_"+n](),a=q,d=k+1;d<l.length-1;d++)a=isNaN(Number(l[d]))?a["get_"+l[d]]():a[Number(l[d])];m=l[l.length-1];a[m]=e;h(v,n,q)}else{for(var v=a,d=0;d<l.length-1;d++)v=Array.isArray(v)&&!isNaN(Number(l[d]))?v[Number(l[d])]:v["get_"+l[d]]();m=l[l.length-1];h(v,m,e)}g=this.updatePropertyGrid(new J(this._212))}catch(s){g.push(b),f=s}0===g.length&&b._3!==e&&g.push(b);return{changedProperties:g,exception:f}}};l.updatePropertyGrid=
function(e){var a=[],l=[];c(this,this._159,a,e._159);if(0!=a.length)for(var b=0;b<a.length;b++)a[b].property._3=a[b].value,l.push(a[b].property);g(this._159,e._159);k(this._159,e._159);return l};this._212=a;void 0==f&&(f="");void 0==d&&(d="");this._159=new A(f,d,a,!1);e(this._159,a,d)},s=function(a,f,d,k){function g(a,c,l){if("string"===typeof a)try{a=JSON.parse(a)}catch(b){}d&&("error"===c&&void 0==a.errorMessage&&""===a.responseText&&(a.errorMessage="Unknown service error OR service is unavailable."),
d(a,c,l))}var h=s.prototype;h.get_ActionName=function(){return this._371};h._84=function(){var a=$.extend(!0,{},this._94);a.success=this._400;a.error=this._334;return a};b.s(a);""===a&&b.te("Action name can not be empty.");void 0!=f&&b.f(f,"Success callback must be defined as function.");void 0!=d&&b.f(d,"Error callback must be defined as function.");this._371=a;this._334=g;this._400=function(a,c,l){if("string"===typeof a)try{a=JSON.parse(a)}catch(b){}a.success?f&&f(a,c,l):g(a,c,l)};this._94=k},G=
function(a,f){var d=G.prototype;d.compositeError=function(a){};d.compositeSuccess=function(a){};d._84=function(){if(0!=this._340.length){for(var a=this._340[0]._84(),b=[],d=0;d<this._340.length;d++)b[d]=this._340[d]._94.data,b[d].requestId=d;var e=this;a.data={requestsData:b};a.success=function(c,a,b){if("string"===typeof c)try{c=JSON.parse(c)}catch(d){}for(a=0;a<c.length;a++)b=parseInt(c[a].requestId),b=e._340[b],void 0!=b._400&&b._400(c[a]);$(e).triggerHandler("compositeSuccess")};a.error=function(c,
a,b){if("string"===typeof c)try{c=JSON.parse(c)}catch(d){}if("object"===typeof c&&c.length)for(a=0;a<c.length;a++)b=parseInt(c[a].requestId),b=e._340[b],void 0!=b._334&&b._334(c[a]);else for("error"===a&&void 0==c.errorMessage&&""===c.responseText&&(c.errorMessage="Unknown service error OR service is unavailable."),a=0;a<e._340.length;a++)b=e._340[a],void 0!=b._334&&b._334(c);$(e).triggerHandler("compositeError")};return a}};this._371=f;b.ac(a,s);this._340=a;delete d.compositeError;delete d.compositeSuccess};
m.extend(G,s);var n=function(a){var f=n.prototype;f.get_ServiceRoute=function(){return this._381};f.addRequest=function(a){b.c(a,s);if(0===this._274)return this.sendRequest(a);this._198.push(a)};f.sendRequests=function(){var a=[],b=this._313();if(0!=b.length)for(var g=0;g<b.length;g++)a.push(this.sendRequest(b[g]));for(g=0;g<this._198.length;g++)a.push(this.sendRequest(this._198[g]));this._198=[];return a};f.sendRequest=function(a){b.tne()};f.bi=function(){this._274++};f.ei=function(){this._274--;
0>this._274&&(this._274=0);if(0===this._274)return this.sendRequests()};f._313=function(){for(var a=[],b=0;b<this._198.length;){var g=this._198[b]._371,h=n._421[g];if(void 0!=h){for(var e=b,c=[];e<this._198.length;)this._198[e]._371===g?(c.push(this._198[e]),this._198.splice(e,1)):e++;a.push(new G(c,h))}else b++}return a};this._381=a;this._274=0;this._198=[]};n.defaultUrlImageService=-1;n.defaultImageService=-1;n._421=function(){};n._421={};n.rcr=function(a,f){b.s(a,f);""!==a&&""!==f||b.tae();void 0!=
n._421[a]&&b.tae();n._421[a]=f};n.rcr("RenderThumbnail","RenderThumbnails");n.rcr("GetImageInfo","GetImagesInfo");var H=function(a){H.superclass.constructor.apply(this,arguments);H.prototype.sendRequest=function(a){var d=a._84();b.ic(d.data,FormData)?d.data.append("sessionId",q._301):(void 0!=d.data?("object"===typeof d.data&&(d.data.sessionId=q._301),d.data=JSON.stringify(d.data)):d.data=JSON.stringify(q._301),d.contentType="application/json");d.url=this._381+"/"+a._371;return{request:a,object:$.ajax(d)}}};
m.extend(H,n);var I=function(a){I.superclass.constructor.apply(this,arguments);I.prototype.sendRequest=function(a){var d=a._84();d.url=this._381;var k=d.data;b.ic(k,FormData)?(k.append("action",a._371),k.append("sessionId",q._301)):(void 0==k&&(k=q._301),"object"===typeof k?(k.sessionId=q._301,k={requestParams:JSON.stringify(k),action:a._371}):k={requestParams:k,action:a._371});d.data=k;return{request:a,object:$.ajax(d)}}};m.extend(I,n);var t=function(a,f,d){function k(a){$(a.evm).triggerHandler("changed");
$(a).triggerHandler("changed")}var g=t.prototype;g.changed=function(a){};g.get_Resolution=function(){return{x:this._130.x,y:this._130.y}};g.set_Resolution=function(a,e){var c;c=void 0==e?{x:a.x,y:a.y}:{x:a,y:e};b.p(c);var l=this._130;if(l.x!==c.x||l.y!==c.y)this._130=c,this._80||k(this)};g.get_InterpolationMode=function(){return this._231};g.set_InterpolationMode=function(a){a=b.e(a,m.WebInterpolationModeEnumJS);a.equals(this._231)||(this._231=a,this._80||k(this))};g.get_SmoothingMode=function(){return this._333};
g.set_SmoothingMode=function(a){a=b.e(a,m.WebSmoothingModeEnumJS);a.equals(this._333)||(this._333=a,this._80||k(this))};g.clone=function(){return new this.constructor(this._130,this._231,this._333)};g.equals=function(a){return b.ic(a,t)?this._130.x===a._130.x&&this._130.y===a._130.y&&this._231.valueOf()===a._231.valueOf()&&this._333.valueOf()===a._333.valueOf():!1};g.isEmpty=function(){return this.equals(new t)};g.beginInit=function(){this._80||(this._80=!0,this._194=this.clone())};g.endInit=function(){this._80&&
(this._80=!1,void 0==this._194||this.equals(this._194)||(this._194=void 0,k(this)))};g.toObject=function(){return this._225()};g._225=function(){return{resolution:this._130,interpolationMode:this._231.valueOf(),smoothingMode:this._333.valueOf()}};void 0==a&&(a={x:0,y:0});b.p(a);this._130={x:a.x,y:a.y};void 0==f&&(f=6);this._231=b.e(f,m.WebInterpolationModeEnumJS);void 0==d&&(d=4);this._333=b.e(d,m.WebSmoothingModeEnumJS);this._80=!1;this._194=void 0;this.evm={};delete g.changed},y=function(){var a=
y.prototype;a.changed=function(a){};a.get_IsColorManagementEnabled=function(){return this._132};a.set_IsColorManagementEnabled=function(a){b.b(a);this._132!==a&&(this._132=a,$(this).triggerHandler("changed"),$(this._192).triggerHandler("changed"))};a.clone=function(){var a=new this.constructor;a._132=this._132;return a};a.equals=function(a){return b.ic(a,y)?this._132===a._132:!1};a.toObject=function(){return this._225()};a._225=function(){return{isColorManagementEnabled:this._132}};this._132=!0;this._192=
{};delete a.changed},E=function(a,f,d){this._55=a;void 0==f&&(f=-1!==n.defaultImageService?n.defaultImageService:n.defaultUrlImageService);-1!==f&&b.c(f,n,"You should specify correct image service OR define the default image service.");this._343=f;void 0==d&&(d=n.defaultAnnotationService);void 0!=d&&(b.c(d,n,"You should specify correct annotation service OR define the default annotation service"),this._178=d);a=E.prototype;a.get_ImageId=function(){return this._55};a.get_ImageService=function(){b.c(this._343,
n,"Image service is not an instance of WebServiceJS class.");return this._343};a.get_AnnotationService=function(){b.c(this._178,n,"Image annotating service is not an instance of WebServiceJS class.");return this._178};a.equals=function(a){return this===a?!0:b.ic(a,E)&&this._55===a._55?this._343._381===a._343._381&&(void 0==this._178&&void 0==a._178||void 0!=this._178&&void 0!=a._178&&this._178._381===a._178._381):!1};a._42=function(a,d,h,e,c){b.n(a);void 0!=d&&b.c(d,t);void 0!=h&&b.c(h,y);var l={};
l.imageInfo={imageId:this._55,pageIndex:a};void 0==d||d.isEmpty()||(l.renderingSettings=d._225());void 0!=h&&(l.decodingSettings=h._225());a=new s("GetImageInfo",e,c,{type:"POST",data:l});return this._343.addRequest(a)};a._13=function(a,d,h,e,c,l,f,u,B){c=b.e(c,m.WebImageTypeEnumJS);b.n(a,d,h);b.b(e);void 0!=l&&b.c(l,t);void 0!=f&&b.c(f,y);var r={};r.imageInfo={imageId:this._55,pageIndex:a};r.thumbnailSize={width:d,height:h};r.imageType=c.valueOf();r.useCache=e;r.applicationUrl=window.location.href;
void 0==l||l.isEmpty()||(r.renderingSettings=l._225());void 0!=f&&(r.decodingSettings=f._225());a=new s("RenderThumbnail",u,B,{type:"POST",data:r});this._343.addRequest(a)};a._338=function(a,d,h,e,c,l,f,u,B,r,p,n,q){B=b.e(B,m.WebImageTypeEnumJS);b.n(a,d,h,e,c);b.b(f,u);b.p(l);void 0!=r&&b.c(r,t);void 0!=p&&b.c(p,y);var z={};z.imageInfo={imageId:this._55,pageIndex:a};z.tileSize={width:e,height:c};z.imagePoint={x:d,y:h};z.scale=l;z.useCache=f;z.applicationUrl=window.location.href;z.renderNeighbourTiles=
u;z.imageType=B.valueOf();void 0==r||r.isEmpty()||(z.renderingSettings=r._225());void 0!=p&&(z.decodingSettings=p._225());a=new s("RenderImageTile",n,q,{type:"POST",data:z});return this._343.sendRequest(a)};a._165=function(a,d,h,e,c,l,f,u,B){c=b.e(c,m.WebImageTypeEnumJS);b.n(a,d,h);b.p(e);void 0!=l&&b.c(l,t);void 0!=f&&b.c(f,y);var r={};r.imageInfo={imageId:this._55,pageIndex:a};r.tileSize={width:d,height:h};r.scale=e;r.applicationUrl=window.location.href;r.imageType=c.valueOf();void 0==l||l.isEmpty()||
(r.renderingSettings=l._225());void 0!=f&&(r.decodingSettings=f._225());a=new s("RenderImageTiles",u,B,{type:"POST",data:r});return this._343.sendRequest(a)};a._197=function(a,d,f,e,c){b.n(a);void 0!=d&&b.c(d,t);void 0!=f&&b.c(f,y);var l={};l.imageInfo={imageId:this._55,pageIndex:a};l.applicationUrl=window.location.href;void 0==d||d.isEmpty()||(l.renderingSettings=d._225());void 0!=f&&(l.decodingSettings=f._225());a=new s("GetImageAsBase64String",e,c,{type:"POST",data:l});return this._343.sendRequest(a)}},
w=function(a,f){function d(a){$(a._242.evm).on("changed."+a._354,function(){k(a)})}function k(a){!1!==a._91&&a.ci("rsc");$(a).triggerHandler("renderingSettingsChanged",void 0)}function g(a){if(void 0!=a._161)$(a._161._192).on("changed."+a._354,function(){h(a)})}function h(a,e){e&&a.ci("dsc");$(a).triggerHandler("decodingSettingsChanged",void 0)}var e=w.prototype;e.renderingSettingsChanged=function(a){};e.decodingSettingsChanged=function(a){};e.icd=function(a,e){};e.get_ImageId=function(){return this._361._55};
e.get_Size=function(){return void 0==this._175||void 0==this._32?void 0:{width:this._175,height:this._32}};e.get_Resolution=function(){return void 0==this._23||void 0==this._146?void 0:{x:this._23,y:this._146}};e.get_PixelFormat=function(){return this._309};e.get_Source=function(){return this._361};e.get_PageIndex=function(){return this._166};e.get_IsVector=function(){return this._91};e.get_RenderingSettings=function(){return this._242};e.set_RenderingSettings=function(a){b.c(a,t);this._242.equals(a)||
($(this._242.evm).off("."+this._354),this._242=a,d(this),k(this))};e.get_DecodingSettings=function(){return this._161};e.set_DecodingSettings=function(a){void 0!=a&&b.c(a,y);if(!(void 0!=this._161&&this._161.equals(a)||void 0==this._161&&void 0==a)){void 0!=this._161&&$(this._161._192).off("."+this._354);var e=this._161;this._161=a;g(this);h(this,void 0==e&&a._132||void 0==a&&e._132||void 0!=e&&void 0!=a)}};e.get_Guid=function(){return this._354};e.get_IsBad=function(){return this._155};e.equals=
function(a){return this===a?!0:b.ic(a,w)?a._166===this._166&&this._361.equals(a._361):!1};e.renderTile=function(a,e,b,d,f,g,h,k,m){this._129(a,e,b,d,f,g,!1,h,k,m)};e.renderTileWithNeighbours=function(a,e,b,d,f,g,h,k){this._129(a,e,b,d,f,!0,!0,g,h,k)};e.renderTiles=function(a,e,b,d,f,g){function h(a){a.image=k;a.renderingSettings=m;void 0!=n&&(a.decodingSettings=n)}var k=this,m=this._242.clone(),n;void 0!=this._161&&(n=this._161.clone());return this._361._165(this._166,a,e,b,d,m,n,function(a){h(a);
f&&f(a)},function(a){h(a);a.blocked||(k._155=!0);g&&g(a)})};e.renderThumbnail=function(a,e,b,d,f,g){function h(b){b.image=k;b.width=a;b.height=e;b.renderingSettings=m;void 0!=n&&(b.decodingSettings=n)}var k=this,m=this._242.clone(),n;void 0!=this._161&&(n=this._161.clone());this._361._13(this._166,a,e,b,d,m,n,function(a){h(a);void 0!=a.imageParam&&k._26(a.imageParam);f&&f(a)},function(a){h(a);void 0!=a.imageParam&&k._26(a.imageParam);a.blocked||(k._155=!0);g&&g(a)})};e.getImageInfo=function(a,e){function b(a){a.image=
d;a.renderingSettings=f;void 0!=g&&(a.decodingSettings=g)}var d=this,f=this._242.clone(),g;void 0!=this._161&&(g=this._161.clone());return this._361._42(this._166,this._242,this._161,function(e){b(e);d._26(e);a&&a(e)},function(a){b(a);d._26(a);a.blocked||(d._155=!0);e&&e(a)})};e.getImageAsBase64String=function(a,e){function b(a){a.image=d;a.renderingSettings=f;void 0!=g&&(a.decodingSettings=g)}var d=this,f=this._242.clone(),g;void 0!=this._161&&(g=this._161.clone());return this._361._197(this._166,
f,g,function(e){b(e);a&&a(e)},function(a){b(a);a.blocked||(d._155=!0);e&&e(a)})};e.cto=function(){return{imageId:this._361._55,pageIndex:this._166}};e.csto=function(){var a={};!1===this._91||this._242.isEmpty()||(a.renderingSettings=this._242._225());void 0!=this._161&&(a.decodingSettings=this._161._225());return a};e.gi=function(){return this._89};e.ci=function(a){void 0==a&&(a="dc");this._89=q.guid();"dsc"!==a&&(this._146=this._23=this._32=this._175=void 0,this._155=!1);a={i:this,d:a};$(this.evm).triggerHandler("icd",
a)};e._129=function(a,e,d,f,g,h,k,m,n,q){function s(b){b.image=y;b.pos={x:a,y:e};b.size={width:d,height:f};b.scale=g;b.renderingSettings=v;void 0!=w&&(b.decodingSettings=w)}var t=Infinity,x=t;void 0!=this._175&&0!==this._175&&0!==this._32&&(t=this._175,x=this._32);(0>a||a>=t||0>e||e>=x)&&b.te("Tile must have coordinates inside the image.");var y=this,v=this._242.clone(),w;void 0!=this._161&&(w=this._161.clone());return this._361._338(this._166,a,e,d,f,g,h,k,m,v,w,function(a){s(a);n&&n(a)},function(a){s(a);
a.blocked||(y._155=!0);q&&q(a)})};e._26=function(a){if(void 0==this._175||void 0==this._32||void 0==this._23||void 0==this._146){var e=a.imageSize,b=a.imageResolution;if(void 0!=e&&void 0!=b){this._175=Number(e.width);this._32=Number(e.height);this._23=Number(b.width);this._146=Number(b.height);this._91=a.isVector;try{this._309=new m.WebPixelFormatEnumJS(a.pixelFormat)}catch(d){this._309=new m.WebPixelFormatEnumJS(0)}if(0===this._175||0===this._32)this._155=!0}}a.pixelFormat=this._309};b.c(a,E);b.n(f);
this._361=a;this._166=f;this._354=q.guid();this._89=q.guid();this._242=new t;d(this);this._161;this.evm={};this._175;this._32;this._23;this._146;this._309;this._91;this._155=!1;delete e.decodingSettingsChanged;delete e.renderingSettingsChanged;delete e.icd};n.defaultImageCollectionService=-1;var K=function(){function a(a){b.c(a,n,"Image collection service is not correct.")}function f(a){for(var b=a.imageInfos,d=[],f=[],g=0;g<b.length;g++){var h=b[g].imageId,k=d[h];void 0==k&&(k=new E(h),d[h]=k);f.push(new w(k,
b[g].pageIndex))}a.images=f}function d(a,c){var d={};b.ad(c,function(c){b.n(c);(0>c||c>=a._409.length)&&b.toe();void 0==d[c]&&(d[c]=1)});var f=[],g;for(g in d)f.push(Number(g));return f}function k(a,c,d){var f=!1,g=!1,h=!1;for(void 0==d._361._178&&(h=!0);c<a.length;c++){var k=a[c],m;a:{m=k;var n=d,q=!f;if(m._361.equals(n._361)&&(m._166===n._166&&b.te("Image already exists in collection."),q)){n._361=m._361;n._361._343=m._361._343;n._361._178=m._361._178;m=!0;break a}m=!1}m&&(h=g=f=!0);g||d._361._343._381!==
k._361._343._381||(d._361._343=k._361._343,g=!0);h||void 0==k._361._178||d._361._178._381!==k._361._178._381||(d._361._178=k._361._178,h=!0)}}function g(a,b){for(var d=-1,f=0;f<a._409.length;f++)if(a._409[f]._354==b){d=f;break}return d}var h=K.prototype;h.changing=function(a,b){};h.changed=function(a,b){};h.get_Count=function(){return this._409.length};h.get_Image=function(a){b.n(a);if(0<=a&&a<this._409.length)return this._409[a];b.toe()};h.indexOf=function(a){"string"!==typeof a&&b.c(a,w);return g(this,
"string"===typeof a?a:a._354)};h.clear=function(){if(0!==this._409.length){var a={actionName:"clear",images:this.toArray()};this._133(a);this._409=[];this._388(a)}};h.add=function(a){this.insert(this._409.length,a)};h.addRange=function(a){this.insertRange(this._409.length,a)};h.insert=function(a,c){b.n(a);b.c(c,w);if(0<=a&&a<=this._409.length){k(this._409,0,c);var d={actionName:"insert",imageIndex:a,image:c};this._133(d);this._409.splice(a,0,c);this._388(d)}else b.toe()};h.insertRange=function(a,
c){var d=!0;b.ic(c,K)&&(c=c._409,d=!1);b.n(a);d&&b.ac(c,w);if(0<=a&&a<=this._409.length){for(var f=c.length,d=c.concat(this._409),f=f-1;0<=f;f--)k(d,f+1,c[f]);d={actionName:"insertRange",imageIndex:a,images:c};this._133(d);for(f=0;f<c.length;f++)this._409.splice(a+f,0,c[f]);this._388(d)}else b.toe()};h.removeAt=function(a){b.n(a);if(0<=a&&a<this._409.length&&0!=this._409.length){var c={actionName:"removeAt",imageIndex:a,image:this._409[a]};this._133(c);this._409.splice(a,1);this._388(c)}else b.toe()};
h.remove=function(a){b.c(a,w);a=g(this,a._354);-1!==a?this.removeAt(a):b.te("Image does not exist.")};h.removeImages=function(a){var c=[],d=this;b.ad(a,function(a){b.c(a,w);a=g(d,a._354);-1!==a?c.push(a):b.te("Image does not exist.")});this.removeRange(c)};h.removeRange=function(a){a=d(this,a);for(var b=[],f=0;f<a.length;f++)b.push(this._409[a[f]]);b={actionName:"removeRange",imagesIndexes:a,images:b};this._133(b);for(f=a.length-1;0<=f;f--)this._409.splice(a[f],1);this._388(b)};h.set=function(a,c){b.n(a);
b.c(c,w);if(0<=a&&a<this._409.length&&0!=this._409.length){var d={actionName:"set",imageIndex:a,image:c,previousImage:this._409[a]};this._133(d);this._16=!1;this.removeAt(a);this.insert(a,c);this._16=!0;this._388(d)}else b.toe()};h.toArray=function(){return[].concat(this._409)};h.setRenderingSettings=function(a){b.c(a,t);for(var c=0;c<this._409.length;c++)this._409[c].set_RenderingSettings(a.clone())};h.setDecodingSettings=function(a){void 0!=a&&b.c(a,y);if(void 0!=a)for(var c=0;c<this._409.length;c++)this._409[c].set_DecodingSettings(a.clone());
else for(c=0;c<this._409.length;c++)this._409[c].set_DecodingSettings()};h.getImageFilesInfos=function(d,c,g,h){try{b.ad(d,b.s)}catch(k){b.te("fileUrls parameter must be an array of strings")}h=n.defaultImageCollectionService;b.ic(c,n)&&(h=c);a(h);d=new s("GetImageFileInfo",function(a,d,e){f(a);b.isf(c)&&c(a,d,e)},g,{type:"POST",data:{fileIds:d}});return h.sendRequest(d)};h.openFile=function(a,c,d,f){b.s(a);return this.openFiles([a],c,d,f)};h.openFiles=function(a,c,d,f){b.ic(c,n)&&(f=c);var g=this;
return this.getImageFilesInfos(a,function(a,d,e){g.clear();g.addRange(a.images);b.isf(c)&&c(a,d,e)},d,f)};h.saveState=function(b,c,d){void 0==d&&(d=n.defaultImageCollectionService);a(d);for(var f=this.toArray(),g=[],h=0;h<f.length;h++){var k=f[h].get_Source();g.push({imageId:k._55,pageIndex:f[h]._166})}b=new s("SaveState",b,c,{type:"POST",data:{imageInfos:g}});return d.sendRequest(b)};h.loadState=function(d,c,g){void 0==g&&(g=n.defaultImageCollectionService);a(g);c=new s("LoadState",function(a,c,
g){f(a);b.isf(d)&&d(a,c,g)},c,{type:"POST",data:{}});return g.sendRequest(c)};h._133=function(a){this._16&&($(this.evm).triggerHandler("changing",a),$(this).triggerHandler("changing",a))};h._388=function(a){this._16&&($(this.evm).triggerHandler("changed",a),$(this).triggerHandler("changed",a))};this._409=[];this.evm={};this._16=!0;delete h.changing;delete h.changed};m.pv=b;m.WebImagingEnviromentJS=q;m.EnumGenerator=C;m.WebEnumItemBase=D;m.WebFlagsEnumItemBase=F;m.WebPropertyInfoJS=A;m.WebPropertyGridJS=
J;m.WebRequestJS=s;m.WebCompositeRequestJS=G;m.WebServiceJS=n;m.WebServiceControllerJS=H;m.WebServiceHandlerJS=I;m.WebDecodingSettingsJS=y;m.WebRenderingSettingsJS=t;m.WebImageSourceJS=E;m.WebImageJS=w;m.WebImageCollectionJS=K})(x.Shared||(x.Shared={}))})(Vintasoft||(Vintasoft={}));
