//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.81.0.
// 
namespace LibaryXMLAutoModelXmlSql.Model.Trebovanie {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Incass {
        
        private int d851Res_1Field;
        
        private bool d851Res_1FieldSpecified;
        
        private int d850IncassField;
        
        private bool d850IncassFieldSpecified;
        
        private int d851IncassField;
        
        private bool d851IncassFieldSpecified;
        
        private double summField;
        
        private bool summFieldSpecified;
        
        private int d270IshIncassField;
        
        private bool d270IshIncassFieldSpecified;
        
        private System.DateTime dateCreateField;
        
        private bool dateCreateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D851Res_1 {
            get {
                return this.d851Res_1Field;
            }
            set {
                this.d851Res_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D851Res_1Specified {
            get {
                return this.d851Res_1FieldSpecified;
            }
            set {
                this.d851Res_1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D850Incass {
            get {
                return this.d850IncassField;
            }
            set {
                this.d850IncassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D850IncassSpecified {
            get {
                return this.d850IncassFieldSpecified;
            }
            set {
                this.d850IncassFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D851Incass {
            get {
                return this.d851IncassField;
            }
            set {
                this.d851IncassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D851IncassSpecified {
            get {
                return this.d851IncassFieldSpecified;
            }
            set {
                this.d851IncassFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Summ {
            get {
                return this.summField;
            }
            set {
                this.summField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SummSpecified {
            get {
                return this.summFieldSpecified;
            }
            set {
                this.summFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D270IshIncass {
            get {
                return this.d270IshIncassField;
            }
            set {
                this.d270IshIncassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D270IshIncassSpecified {
            get {
                return this.d270IshIncassFieldSpecified;
            }
            set {
                this.d270IshIncassFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                this.dateCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCreateSpecified {
            get {
                return this.dateCreateFieldSpecified;
            }
            set {
                this.dateCreateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Reshenie {
        
        private Incass[] incassField;
        
        private int d865Field;
        
        private bool d865FieldSpecified;
        
        private int d270Field;
        
        private bool d270FieldSpecified;
        
        private int n1Field;
        
        private bool n1FieldSpecified;
        
        private double summField;
        
        private bool summFieldSpecified;
        
        private double n120Field;
        
        private bool n120FieldSpecified;
        
        private int d850ResField;
        
        private bool d850ResFieldSpecified;
        
        private int d851ResField;
        
        private bool d851ResFieldSpecified;
        
        private int d865ResField;
        
        private bool d865ResFieldSpecified;
        
        private int d270IshResField;
        
        private bool d270IshResFieldSpecified;
        
        private System.DateTime dateCreateField;
        
        private bool dateCreateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Incass")]
        public Incass[] Incass {
            get {
                return this.incassField;
            }
            set {
                this.incassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D865 {
            get {
                return this.d865Field;
            }
            set {
                this.d865Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D865Specified {
            get {
                return this.d865FieldSpecified;
            }
            set {
                this.d865FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D270 {
            get {
                return this.d270Field;
            }
            set {
                this.d270Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D270Specified {
            get {
                return this.d270FieldSpecified;
            }
            set {
                this.d270FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int N1 {
            get {
                return this.n1Field;
            }
            set {
                this.n1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool N1Specified {
            get {
                return this.n1FieldSpecified;
            }
            set {
                this.n1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Summ {
            get {
                return this.summField;
            }
            set {
                this.summField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SummSpecified {
            get {
                return this.summFieldSpecified;
            }
            set {
                this.summFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double N120 {
            get {
                return this.n120Field;
            }
            set {
                this.n120Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool N120Specified {
            get {
                return this.n120FieldSpecified;
            }
            set {
                this.n120FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D850Res {
            get {
                return this.d850ResField;
            }
            set {
                this.d850ResField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D850ResSpecified {
            get {
                return this.d850ResFieldSpecified;
            }
            set {
                this.d850ResFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D851Res {
            get {
                return this.d851ResField;
            }
            set {
                this.d851ResField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D851ResSpecified {
            get {
                return this.d851ResFieldSpecified;
            }
            set {
                this.d851ResFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D865Res {
            get {
                return this.d865ResField;
            }
            set {
                this.d865ResField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D865ResSpecified {
            get {
                return this.d865ResFieldSpecified;
            }
            set {
                this.d865ResFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D270IshRes {
            get {
                return this.d270IshResField;
            }
            set {
                this.d270IshResField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D270IshResSpecified {
            get {
                return this.d270IshResFieldSpecified;
            }
            set {
                this.d270IshResFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                this.dateCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCreateSpecified {
            get {
                return this.dateCreateFieldSpecified;
            }
            set {
                this.dateCreateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TableSysNumReshen {
        
        private Reshenie reshenieField;
        
        private int d270Field;
        
        private bool d270FieldSpecified;
        
        private int idStatus_1Field;
        
        private bool idStatus_1FieldSpecified;
        
        private string errorReshenieField;
        
        private System.DateTime dateBlokReshenieField;
        
        private bool dateBlokReshenieFieldSpecified;
        
        private int idStatus_2Field;
        
        private bool idStatus_2FieldSpecified;
        
        private string errorIncassField;
        
        private System.DateTime dateBlokIncassField;
        
        private bool dateBlokIncassFieldSpecified;
        
        private System.DateTime dataCreateField;
        
        private bool dataCreateFieldSpecified;
        
        /// <remarks/>
        public Reshenie Reshenie {
            get {
                return this.reshenieField;
            }
            set {
                this.reshenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int D270 {
            get {
                return this.d270Field;
            }
            set {
                this.d270Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D270Specified {
            get {
                return this.d270FieldSpecified;
            }
            set {
                this.d270FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdStatus_1 {
            get {
                return this.idStatus_1Field;
            }
            set {
                this.idStatus_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdStatus_1Specified {
            get {
                return this.idStatus_1FieldSpecified;
            }
            set {
                this.idStatus_1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorReshenie {
            get {
                return this.errorReshenieField;
            }
            set {
                this.errorReshenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateBlokReshenie {
            get {
                return this.dateBlokReshenieField;
            }
            set {
                this.dateBlokReshenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateBlokReshenieSpecified {
            get {
                return this.dateBlokReshenieFieldSpecified;
            }
            set {
                this.dateBlokReshenieFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdStatus_2 {
            get {
                return this.idStatus_2Field;
            }
            set {
                this.idStatus_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdStatus_2Specified {
            get {
                return this.idStatus_2FieldSpecified;
            }
            set {
                this.idStatus_2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorIncass {
            get {
                return this.errorIncassField;
            }
            set {
                this.errorIncassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateBlokIncass {
            get {
                return this.dateBlokIncassField;
            }
            set {
                this.dateBlokIncassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateBlokIncassSpecified {
            get {
                return this.dateBlokIncassFieldSpecified;
            }
            set {
                this.dateBlokIncassFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DataCreate {
            get {
                return this.dataCreateField;
            }
            set {
                this.dataCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataCreateSpecified {
            get {
                return this.dataCreateFieldSpecified;
            }
            set {
                this.dataCreateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SysNum {
        
        private TableSysNumReshen[] tableSysNumReshenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TableSysNumReshen")]
        public TableSysNumReshen[] TableSysNumReshen {
            get {
                return this.tableSysNumReshenField;
            }
            set {
                this.tableSysNumReshenField = value;
            }
        }
    }
}
