// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>LibaryXMLAuto.Inventarization.ModelComparableUserAllSystem</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>True</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace LibaryXMLAuto.Inventarization.ModelComparableUserAllSystem
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    /// <summary>
    /// Модель сравнение пользователей со всеми системами
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ModelComparableUser
    {

        private List<FullModelUserAllSystem> fullModelUserAllSystemField;

        private List<GroupActiveDirectory> groupActiveDirectoryField;

        private List<WorkStationActiveDirectory> workStationActiveDirectoryField;

        /// <summary>
        /// ModelComparableUser class constructor
        /// </summary>
        public ModelComparableUser()
        {
            this.workStationActiveDirectoryField = new List<WorkStationActiveDirectory>();
            this.groupActiveDirectoryField = new List<GroupActiveDirectory>();
            this.fullModelUserAllSystemField = new List<FullModelUserAllSystem>();
        }

        [System.Xml.Serialization.XmlElementAttribute("FullModelUserAllSystem", IsNullable = true, Order = 0)]
        public List<FullModelUserAllSystem> FullModelUserAllSystem
        {
            get
            {
                return this.fullModelUserAllSystemField;
            }
            set
            {
                this.fullModelUserAllSystemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("GroupActiveDirectory", Order = 1)]
        public List<GroupActiveDirectory> GroupActiveDirectory
        {
            get
            {
                return this.groupActiveDirectoryField;
            }
            set
            {
                this.groupActiveDirectoryField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("WorkStationActiveDirectory", Order = 2)]
        public List<WorkStationActiveDirectory> WorkStationActiveDirectory
        {
            get
            {
                return this.workStationActiveDirectoryField;
            }
            set
            {
                this.workStationActiveDirectoryField = value;
            }
        }
    }

    /// <summary>
    /// Модель пользователей Лотус
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class FullModelUserAllSystem
    {

        /// <summary>
        /// Системе пользователей из какой системы
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SystemDataBase { get; set; }

        /// <summary>
        /// Фамилия
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Surname { get; set; }

        /// <summary>
        /// Имя
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name { get; set; }

        /// <summary>
        /// Отчество
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Patronymic { get; set; }

        /// <summary>
        /// Полное имя
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName { get; set; }

        /// <summary>
        /// Табельный номер
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PersonnelNumber { get; set; }

        /// <summary>
        /// Отдел
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Department { get; set; }

        /// <summary>
        /// Должность
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string JobTitle { get; set; }

        /// <summary>
        /// Чин
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ranks { get; set; }

        /// <summary>
        /// Телефон
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Telephon { get; set; }

        /// <summary>
        /// Наименование почты
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameMail { get; set; }

        /// <summary>
        /// Комната
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Room { get; set; }

        /// <summary>
        /// Контроль аккаунта
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int UserAccountControl { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserAccountControlSpecified { get; set; }

        /// <summary>
        /// Наименование группы
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GroupName { get; set; }

    }

    /// <summary>
    /// Группы AD
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class GroupActiveDirectory
    {

        /// <summary>
        /// Наименование группы
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameGroup { get; set; }

        /// <summary>
        /// Описание группы
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InfoGroup { get; set; }

        /// <summary>
        /// Управляется группа
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ControlledGroup { get; set; }

    }

    /// <summary>
    /// Рабочии станции AD
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class WorkStationActiveDirectory
    {

        /// <summary>
        /// Наименование рабочей станции
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameWorkStation { get; set; }

        /// <summary>
        /// DNS имя
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DnsName { get; set; }

        /// <summary>
        /// Описание
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Info { get; set; }

        /// <summary>
        /// Управляется пользователем
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ControlledUser { get; set; }

        /// <summary>
        /// Наименование Windows
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WindowsName { get; set; }

        /// <summary>
        /// Версия Windows
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WindowsVersion { get; set; }

        /// <summary>
        /// Размещение
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Room { get; set; }

    }
}
