//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabaseAutomation.Automation.BaseLogica.XsdAuto.FullShemeModel {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AutoWebPage {
        
        private TaxJournalAutoWebPage[] taxJournalAutoWebPageField;
        
        private TaxJournal121AutoWebPage[] taxJournal121AutoWebPageField;
        
        private AddUlFace[] addUlFaceField;
        
        private ModelTree[] modelTreeField;
        
        private ModelKbkOnKbk[] modelKbkOnKbkField;
        
        private HelpKbkAuto[] helpKbkAutoField;
        
        private AllJournal129[] allJournal129Field;
        
        private SignatureBoss[] signatureBossField;
        
        private Documen2NDFLIdentification[] documen2NDFLIdentificationField;
        
        private FormulNdfl[] formulNdflField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxJournalAutoWebPage")]
        public TaxJournalAutoWebPage[] TaxJournalAutoWebPage {
            get {
                return this.taxJournalAutoWebPageField;
            }
            set {
                this.taxJournalAutoWebPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxJournal121AutoWebPage")]
        public TaxJournal121AutoWebPage[] TaxJournal121AutoWebPage {
            get {
                return this.taxJournal121AutoWebPageField;
            }
            set {
                this.taxJournal121AutoWebPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddUlFace")]
        public AddUlFace[] AddUlFace {
            get {
                return this.addUlFaceField;
            }
            set {
                this.addUlFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModelTree")]
        public ModelTree[] ModelTree {
            get {
                return this.modelTreeField;
            }
            set {
                this.modelTreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModelKbkOnKbk")]
        public ModelKbkOnKbk[] ModelKbkOnKbk {
            get {
                return this.modelKbkOnKbkField;
            }
            set {
                this.modelKbkOnKbkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HelpKbkAuto")]
        public HelpKbkAuto[] HelpKbkAuto {
            get {
                return this.helpKbkAutoField;
            }
            set {
                this.helpKbkAutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllJournal129")]
        public AllJournal129[] AllJournal129 {
            get {
                return this.allJournal129Field;
            }
            set {
                this.allJournal129Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SignatureBoss")]
        public SignatureBoss[] SignatureBoss {
            get {
                return this.signatureBossField;
            }
            set {
                this.signatureBossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Documen2NDFLIdentification")]
        public Documen2NDFLIdentification[] Documen2NDFLIdentification {
            get {
                return this.documen2NDFLIdentificationField;
            }
            set {
                this.documen2NDFLIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormulNdfl")]
        public FormulNdfl[] FormulNdfl {
            get {
                return this.formulNdflField;
            }
            set {
                this.formulNdflField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TaxJournalAutoWebPage {
        
        private System.Nullable<System.DateTime> dateIzveshenieField;
        
        private System.Nullable<bool> isLk3Field;
        
        private System.Nullable<bool> isMailField;
        
        private System.Nullable<bool> isPrintField;
        
        private System.Nullable<bool> isTksField;
        
        private System.Nullable<System.DateTime> dataCreateField;
        
        private System.Nullable<int> idDeloField;
        
        private System.Nullable<int> idField;
        
        private string logicsButtonField;
        
        private string loginUserField;
        
        private string innField;
        
        private string kppField;
        
        private string nameFaceField;
        
        private string fidField;
        
        private string typeDocumentField;
        
        private string messageInfoField;
        
        private string extensionsField;
        
        public TaxJournalAutoWebPage() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateIzveshenie {
            get {
                return this.dateIzveshenieField;
            }
            set {
                this.dateIzveshenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsLk3 {
            get {
                return this.isLk3Field;
            }
            set {
                this.isLk3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsMail {
            get {
                return this.isMailField;
            }
            set {
                this.isMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsPrint {
            get {
                return this.isPrintField;
            }
            set {
                this.isPrintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsTks {
            get {
                return this.isTksField;
            }
            set {
                this.isTksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataCreate {
            get {
                return this.dataCreateField;
            }
            set {
                this.dataCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdDelo {
            get {
                return this.idDeloField;
            }
            set {
                this.idDeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LoginUser {
            get {
                return this.loginUserField;
            }
            set {
                this.loginUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFace {
            get {
                return this.nameFaceField;
            }
            set {
                this.nameFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeDocument {
            get {
                return this.typeDocumentField;
            }
            set {
                this.typeDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TaxJournal121AutoWebPage {
        
        private System.Nullable<int> idField;
        
        private System.Nullable<bool> isLk3Field;
        
        private System.Nullable<bool> isMailField;
        
        private System.Nullable<bool> isPrintField;
        
        private System.Nullable<bool> isTksField;
        
        private string logicsButtonField;
        
        private System.Nullable<System.DateTime> dateIzveshenieField;
        
        private System.Nullable<System.DateTime> dataCreateField;
        
        private System.Nullable<System.DateTime> dateFinishDeclarationField;
        
        private System.Nullable<System.DateTime> dateStartDeclarationField;
        
        private System.Nullable<System.DateTime> dateFinishCheckField;
        
        private System.Nullable<System.DateTime> dateStartCheckField;
        
        private System.Nullable<int> regNumDeclarationField;
        
        private System.Nullable<int> godField;
        
        private System.Nullable<int> counDayField;
        
        private string nameKndField;
        
        private string kndField;
        
        private string loginUserField;
        
        private string fidField;
        
        private string innField;
        
        private string nameFaceField;
        
        private string periodField;
        
        private string typeDocumentField;
        
        private string extensionsField;
        
        private string messageInfoField;
        
        public TaxJournal121AutoWebPage() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsLk3 {
            get {
                return this.isLk3Field;
            }
            set {
                this.isLk3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsMail {
            get {
                return this.isMailField;
            }
            set {
                this.isMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsPrint {
            get {
                return this.isPrintField;
            }
            set {
                this.isPrintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsTks {
            get {
                return this.isTksField;
            }
            set {
                this.isTksField = value;
            }
        }
        
        /// <remarks/>
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateIzveshenie {
            get {
                return this.dateIzveshenieField;
            }
            set {
                this.dateIzveshenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataCreate {
            get {
                return this.dataCreateField;
            }
            set {
                this.dataCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFinishDeclaration {
            get {
                return this.dateFinishDeclarationField;
            }
            set {
                this.dateFinishDeclarationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateStartDeclaration {
            get {
                return this.dateStartDeclarationField;
            }
            set {
                this.dateStartDeclarationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFinishCheck {
            get {
                return this.dateFinishCheckField;
            }
            set {
                this.dateFinishCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateStartCheck {
            get {
                return this.dateStartCheckField;
            }
            set {
                this.dateStartCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RegNumDeclaration {
            get {
                return this.regNumDeclarationField;
            }
            set {
                this.regNumDeclarationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> God {
            get {
                return this.godField;
            }
            set {
                this.godField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CounDay {
            get {
                return this.counDayField;
            }
            set {
                this.counDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameKnd {
            get {
                return this.nameKndField;
            }
            set {
                this.nameKndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Knd {
            get {
                return this.kndField;
            }
            set {
                this.kndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LoginUser {
            get {
                return this.loginUserField;
            }
            set {
                this.loginUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFace {
            get {
                return this.nameFaceField;
            }
            set {
                this.nameFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeDocument {
            get {
                return this.typeDocumentField;
            }
            set {
                this.typeDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AddUlFace {
        
        private System.Nullable<int> idUlField;
        
        private string logicsButtonField;
        
        private string innUlField;
        
        private string fullStatusField;
        
        public AddUlFace() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUl {
            get {
                return this.idUlField;
            }
            set {
                this.idUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InnUl {
            get {
                return this.innUlField;
            }
            set {
                this.innUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullStatus {
            get {
                return this.fullStatusField;
            }
            set {
                this.fullStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelTree {
        
        private System.DateTime dateCreateField;
        
        private System.Nullable<int> idModelField;
        
        private System.Nullable<int> idUlField;
        
        private string logicsButtonField;
        
        private string innUlField;
        
        private string treeField;
        
        private string statusModelField;
        
        private string nameTemplateField;
        
        public ModelTree() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public System.DateTime DateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                this.dateCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdModel {
            get {
                return this.idModelField;
            }
            set {
                this.idModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdUl {
            get {
                return this.idUlField;
            }
            set {
                this.idUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Button")]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InnUl {
            get {
                return this.innUlField;
            }
            set {
                this.innUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tree {
            get {
                return this.treeField;
            }
            set {
                this.treeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusModel {
            get {
                return this.statusModelField;
            }
            set {
                this.statusModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameTemplate {
            get {
                return this.nameTemplateField;
            }
            set {
                this.nameTemplateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelKbkOnKbk {
        
        private int idClarificationField;
        
        private long idDocField;
        
        private decimal paymentField;
        
        private System.DateTime dateCreateField;
        
        private string statusErrorField;
        
        private string innPayerField;
        
        private string kbkIfnsField;
        
        private string kbk100BeforeField;
        
        private string tpPayerBeforeField;
        
        private string statusPayerBeforeField;
        
        private string kbkUtcAfterField;
        
        private string tpPayerUtcAfterField;
        
        private string statusPayerUtcAfterField;
        
        private string innBankField;
        
        private string kppBankField;
        
        private string oktmo105Field;
        
        private string oktmoUfkField;
        
        private string conclusionField;
        
        /// <remarks/>
        public int IdClarification {
            get {
                return this.idClarificationField;
            }
            set {
                this.idClarificationField = value;
            }
        }
        
        /// <remarks/>
        public long IdDoc {
            get {
                return this.idDocField;
            }
            set {
                this.idDocField = value;
            }
        }
        
        /// <remarks/>
        public decimal Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                this.dateCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusError {
            get {
                return this.statusErrorField;
            }
            set {
                this.statusErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InnPayer {
            get {
                return this.innPayerField;
            }
            set {
                this.innPayerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KbkIfns {
            get {
                return this.kbkIfnsField;
            }
            set {
                this.kbkIfnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kbk100Before {
            get {
                return this.kbk100BeforeField;
            }
            set {
                this.kbk100BeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TpPayerBefore {
            get {
                return this.tpPayerBeforeField;
            }
            set {
                this.tpPayerBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusPayerBefore {
            get {
                return this.statusPayerBeforeField;
            }
            set {
                this.statusPayerBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KbkUtcAfter {
            get {
                return this.kbkUtcAfterField;
            }
            set {
                this.kbkUtcAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TpPayerUtcAfter {
            get {
                return this.tpPayerUtcAfterField;
            }
            set {
                this.tpPayerUtcAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusPayerUtcAfter {
            get {
                return this.statusPayerUtcAfterField;
            }
            set {
                this.statusPayerUtcAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InnBank {
            get {
                return this.innBankField;
            }
            set {
                this.innBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KppBank {
            get {
                return this.kppBankField;
            }
            set {
                this.kppBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Oktmo105 {
            get {
                return this.oktmo105Field;
            }
            set {
                this.oktmo105Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OktmoUfk {
            get {
                return this.oktmoUfkField;
            }
            set {
                this.oktmoUfkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Conclusion {
            get {
                return this.conclusionField;
            }
            set {
                this.conclusionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class HelpKbkAuto {
        
        private System.Nullable<int> idField;
        
        private int idQbeField;
        
        private string groupColorField;
        
        private string nameGroupPlField;
        
        private string kbkField;
        
        private string descriptionGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdQbe {
            get {
                return this.idQbeField;
            }
            set {
                this.idQbeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GroupColor {
            get {
                return this.groupColorField;
            }
            set {
                this.groupColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameGroupPl {
            get {
                return this.nameGroupPlField;
            }
            set {
                this.nameGroupPlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kbk {
            get {
                return this.kbkField;
            }
            set {
                this.kbkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DescriptionGroup {
            get {
                return this.descriptionGroupField;
            }
            set {
                this.descriptionGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AllJournal129 {
        
        private string logicsButtonField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<int> idDeloField;
        
        private System.DateTime dateErrorField;
        
        private string stateColorField;
        
        private string state_TaxPayerColorField;
        
        private string innField;
        
        private string kppField;
        
        private string nameFaceField;
        
        private string fidField;
        
        private string loginUserField;
        
        private string messageInfoField;
        
        public AllJournal129() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdDelo {
            get {
                return this.idDeloField;
            }
            set {
                this.idDeloField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateError {
            get {
                return this.dateErrorField;
            }
            set {
                this.dateErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StateColor {
            get {
                return this.stateColorField;
            }
            set {
                this.stateColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State_TaxPayerColor {
            get {
                return this.state_TaxPayerColorField;
            }
            set {
                this.state_TaxPayerColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFace {
            get {
                return this.nameFaceField;
            }
            set {
                this.nameFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LoginUser {
            get {
                return this.loginUserField;
            }
            set {
                this.loginUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MessageInfo {
            get {
                return this.messageInfoField;
            }
            set {
                this.messageInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SignatureBoss {
        
        private string logicsButtonField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<bool> isActualField;
        
        private string nameUserField;
        
        private string isSignatureField;
        
        public SignatureBoss() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActual {
            get {
                return this.isActualField;
            }
            set {
                this.isActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsSignature {
            get {
                return this.isSignatureField;
            }
            set {
                this.isSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Documen2NDFLIdentification {
        
        private string logicsButtonField;
        
        private long idDocField;
        
        private System.Nullable<long> idFileField;
        
        private System.Nullable<int> yarsField;
        
        private System.Nullable<int> priznakField;
        
        private System.Nullable<System.DateTime> dateNameUserField;
        
        private System.Nullable<long> fidField;
        
        private System.Nullable<long> idFlField;
        
        private System.Nullable<System.DateTime> dateNameUserUtochField;
        
        private string iNNField;
        
        private string fNameField;
        
        private string iNameField;
        
        private string oNameField;
        
        private string fIOField;
        
        private string documentField;
        
        private string seriaNumberField;
        
        private string innOrganizationField;
        
        private string nameOrganizationField;
        
        private string iNNUtochField;
        
        private string fNameUtochField;
        
        private string iNameUtochField;
        
        private string oNameUtochField;
        
        private string statusSvedField;
        
        private string errorNameStatusField;
        
        public Documen2NDFLIdentification() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        public long IdDoc {
            get {
                return this.idDocField;
            }
            set {
                this.idDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdFile {
            get {
                return this.idFileField;
            }
            set {
                this.idFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Yars {
            get {
                return this.yarsField;
            }
            set {
                this.yarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Priznak {
            get {
                return this.priznakField;
            }
            set {
                this.priznakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateNameUser {
            get {
                return this.dateNameUserField;
            }
            set {
                this.dateNameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdFl {
            get {
                return this.idFlField;
            }
            set {
                this.idFlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateNameUserUtoch {
            get {
                return this.dateNameUserUtochField;
            }
            set {
                this.dateNameUserUtochField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FName {
            get {
                return this.fNameField;
            }
            set {
                this.fNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IName {
            get {
                return this.iNameField;
            }
            set {
                this.iNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OName {
            get {
                return this.oNameField;
            }
            set {
                this.oNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FIO {
            get {
                return this.fIOField;
            }
            set {
                this.fIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SeriaNumber {
            get {
                return this.seriaNumberField;
            }
            set {
                this.seriaNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InnOrganization {
            get {
                return this.innOrganizationField;
            }
            set {
                this.innOrganizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOrganization {
            get {
                return this.nameOrganizationField;
            }
            set {
                this.nameOrganizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INNUtoch {
            get {
                return this.iNNUtochField;
            }
            set {
                this.iNNUtochField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FNameUtoch {
            get {
                return this.fNameUtochField;
            }
            set {
                this.fNameUtochField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string INameUtoch {
            get {
                return this.iNameUtochField;
            }
            set {
                this.iNameUtochField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ONameUtoch {
            get {
                return this.oNameUtochField;
            }
            set {
                this.oNameUtochField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusSved {
            get {
                return this.statusSvedField;
            }
            set {
                this.statusSvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorNameStatus {
            get {
                return this.errorNameStatusField;
            }
            set {
                this.errorNameStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FormulNdfl {
        
        private string logicsButtonField;
        
        private decimal moneyNdflField;
        
        private int countNdflField;
        
        private decimal avgMoneyField;
        
        private int codeNdflField;
        
        private System.Nullable<System.DateTime> dateOgrnField;
        
        private int countFlField;
        
        private string nameSmallField;
        
        private string innField;
        
        private string kppField;
        
        private string statusUlField;
        
        public FormulNdfl() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        public decimal MoneyNdfl {
            get {
                return this.moneyNdflField;
            }
            set {
                this.moneyNdflField = value;
            }
        }
        
        /// <remarks/>
        public int CountNdfl {
            get {
                return this.countNdflField;
            }
            set {
                this.countNdflField = value;
            }
        }
        
        /// <remarks/>
        public decimal AvgMoney {
            get {
                return this.avgMoneyField;
            }
            set {
                this.avgMoneyField = value;
            }
        }
        
        /// <remarks/>
        public int CodeNdfl {
            get {
                return this.codeNdflField;
            }
            set {
                this.codeNdflField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateOgrn {
            get {
                return this.dateOgrnField;
            }
            set {
                this.dateOgrnField = value;
            }
        }
        
        /// <remarks/>
        public int CountFl {
            get {
                return this.countFlField;
            }
            set {
                this.countFlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSmall {
            get {
                return this.nameSmallField;
            }
            set {
                this.nameSmallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusUl {
            get {
                return this.statusUlField;
            }
            set {
                this.statusUlField = value;
            }
        }
    }
}
