//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 

using System;

namespace LibaryXMLAuto.XsdModelAutoGenerate {
    using System.Xml.Serialization;
    using AttributeHelperModelXml;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AutoGenerateSchemes {
        
        private TaxArrears[] taxArrearsField;
        
        private AddressModel[] addressModelField;
        
        private JudicialAct[] judicialActField;

        private FaceStatement[] faceStatementField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxArrears")]
        public TaxArrears[] TaxArrears {
            get {
                return this.taxArrearsField;
            }
            set {
                this.taxArrearsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressModel")]
        public AddressModel[] AddressModel {
            get {
                return this.addressModelField;
            }
            set {
                this.addressModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JudicialAct")]
        public JudicialAct[] JudicialAct {
            get {
                return this.judicialActField;
            }
            set {
                this.judicialActField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FaceStatement")]
        public FaceStatement[] FaceStatement
        {
            get
            {
                return this.faceStatementField;
            }
            set
            {
                this.faceStatementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TaxArrears {
        
        private string innField;
        
        private string kppField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("ИНН", "ИНН")]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("КПП", "КПП")]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AddressModel {
        
        private string fidField;
        
        private string innField;
        
        private string addressField;
        
        private string indexOldField;
        
        private string indexNewField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("ФИД", "ФИД")]
        public string Fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("ИНН", "ИНН")]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("АДРЕС", "АДРЕС")]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("ИНДЕКС СТАРЫЙ", "ИНДЕКС СТАРЫЙ")]
        public string IndexOld {
            get {
                return this.indexOldField;
            }
            set {
                this.indexOldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("ИНДЕКС НОВЫЙ", "ИНДЕКС НОВЫЙ")]
        public string IndexNew {
            get {
                return this.indexNewField;
            }
            set {
                this.indexNewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class JudicialAct {
        
        private string innField;
        
        private string numberAktField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("ИНН", "ИНН")]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("Номер заявления", "Номер заявления")]
        public string NumberAkt {
            get {
                return this.numberAktField;
            }
            set {
                this.numberAktField = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FaceStatement
    {
        private string innField;

        private string numberStatementField;

        private DateTime dateTimetatementField;
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("ИНН", "ИНН")]
        public string Inn
        {
            get
            {
                return this.innField;
            }
            set
            {
                this.innField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("Номер заявления", "Номер заявления")]
        public string NumberStatement
        {
            get
            {
                return this.numberStatementField;
            }
            set
            {
                this.numberStatementField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [DataNames("Дата регистрации заявления в УДиЭА", "Дата регистрации заявления в УДиЭА")]
        public DateTime DateTimeStatement
        {
            get
            {
                return this.dateTimetatementField;
            }
            set
            {
                this.dateTimetatementField = value;
            }
        }

    }
}
