//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace LibaryXMLAutoModelXmlSql.PreCheck.ModelCard {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CardFaceUl {
        
        private FaceUl faceUlField;
        
        private Card cardField;
        
        private BranchUlFace[] branchUlFaceField;
        
        private HistoriUlFace[] historiUlFaceField;
        
        private CashUlFace[] cashUlFaceField;
        
        private CashBankSpr[] cashBankSprField;
        
        private RukAndUcrh[] rukAndUcrhField;
        
        private ImZmTrUl[] imZmTrUlField;
        
        private Active[] activeField;
        
        private Balans[] balansField;
        
        private Profit[] profitField;
        
        private Nds[] ndsField;
        
        private FlRukUcrh[] flRukUcrhField;
        
        private SummaryBankSales[] summaryBankSalesField;
        
        private SummaryBankPurchase[] summaryBankPurchaseField;
        
        /// <remarks/>
        public FaceUl FaceUl {
            get {
                return this.faceUlField;
            }
            set {
                this.faceUlField = value;
            }
        }
        
        /// <remarks/>
        public Card Card {
            get {
                return this.cardField;
            }
            set {
                this.cardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BranchUlFace")]
        public BranchUlFace[] BranchUlFace {
            get {
                return this.branchUlFaceField;
            }
            set {
                this.branchUlFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HistoriUlFace")]
        public HistoriUlFace[] HistoriUlFace {
            get {
                return this.historiUlFaceField;
            }
            set {
                this.historiUlFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CashUlFace")]
        public CashUlFace[] CashUlFace {
            get {
                return this.cashUlFaceField;
            }
            set {
                this.cashUlFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CashBankSpr")]
        public CashBankSpr[] CashBankSpr {
            get {
                return this.cashBankSprField;
            }
            set {
                this.cashBankSprField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RukAndUcrh")]
        public RukAndUcrh[] RukAndUcrh {
            get {
                return this.rukAndUcrhField;
            }
            set {
                this.rukAndUcrhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImZmTrUl")]
        public ImZmTrUl[] ImZmTrUl {
            get {
                return this.imZmTrUlField;
            }
            set {
                this.imZmTrUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Active")]
        public Active[] Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Balans")]
        public Balans[] Balans {
            get {
                return this.balansField;
            }
            set {
                this.balansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Profit")]
        public Profit[] Profit {
            get {
                return this.profitField;
            }
            set {
                this.profitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Nds")]
        public Nds[] Nds {
            get {
                return this.ndsField;
            }
            set {
                this.ndsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FlRukUcrh")]
        public FlRukUcrh[] FlRukUcrh {
            get {
                return this.flRukUcrhField;
            }
            set {
                this.flRukUcrhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SummaryBankSales")]
        public SummaryBankSales[] SummaryBankSales {
            get {
                return this.summaryBankSalesField;
            }
            set {
                this.summaryBankSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SummaryBankPurchase")]
        public SummaryBankPurchase[] SummaryBankPurchase {
            get {
                return this.summaryBankPurchaseField;
            }
            set {
                this.summaryBankPurchaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FaceUl {
        
        private System.Nullable<System.DateTime> dateReshField;
        
        private bool dateReshFieldSpecified;
        
        private string innField;
        
        private string kppField;
        
        private string nameFullField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateResh {
            get {
                return this.dateReshField;
            }
            set {
                this.dateReshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateReshSpecified {
            get {
                return this.dateReshFieldSpecified;
            }
            set {
                this.dateReshFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFull {
            get {
                return this.nameFullField;
            }
            set {
                this.nameFullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Card {
        
        private List1Card[] list1CardField;
        
        private List2Card[] list2CardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("List1Card")]
        public List1Card[] List1Card {
            get {
                return this.list1CardField;
            }
            set {
                this.list1CardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("List2Card")]
        public List2Card[] List2Card {
            get {
                return this.list2CardField;
            }
            set {
                this.list2CardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class List1Card {
        
        private string keysField;
        
        private string keys1Field;
        
        private string parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Keys1 {
            get {
                return this.keys1Field;
            }
            set {
                this.keys1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class List2Card {
        
        private string keysField;
        
        private string parameterField;
        
        private string parameter1Field;
        
        private string parameter2Field;
        
        private string parameter3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parameter1 {
            get {
                return this.parameter1Field;
            }
            set {
                this.parameter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parameter2 {
            get {
                return this.parameter2Field;
            }
            set {
                this.parameter2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parameter3 {
            get {
                return this.parameter3Field;
            }
            set {
                this.parameter3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BranchUlFace {
        
        private System.Nullable<System.DateTime> dataCreateBranchField;
        
        private bool dataCreateBranchFieldSpecified;
        
        private System.Nullable<System.DateTime> dataCloseBranchField;
        
        private bool dataCloseBranchFieldSpecified;
        
        private string indexAddressField;
        
        private string regionAddressField;
        
        private string districtAddressField;
        
        private string townAddressField;
        
        private string localityAddressField;
        
        private string streetAddressField;
        
        private string houseAddressField;
        
        private string bodyAddressField;
        
        private string apartmentAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataCreateBranch {
            get {
                return this.dataCreateBranchField;
            }
            set {
                this.dataCreateBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataCreateBranchSpecified {
            get {
                return this.dataCreateBranchFieldSpecified;
            }
            set {
                this.dataCreateBranchFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataCloseBranch {
            get {
                return this.dataCloseBranchField;
            }
            set {
                this.dataCloseBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataCloseBranchSpecified {
            get {
                return this.dataCloseBranchFieldSpecified;
            }
            set {
                this.dataCloseBranchFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IndexAddress {
            get {
                return this.indexAddressField;
            }
            set {
                this.indexAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegionAddress {
            get {
                return this.regionAddressField;
            }
            set {
                this.regionAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DistrictAddress {
            get {
                return this.districtAddressField;
            }
            set {
                this.districtAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TownAddress {
            get {
                return this.townAddressField;
            }
            set {
                this.townAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocalityAddress {
            get {
                return this.localityAddressField;
            }
            set {
                this.localityAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StreetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseAddress {
            get {
                return this.houseAddressField;
            }
            set {
                this.houseAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BodyAddress {
            get {
                return this.bodyAddressField;
            }
            set {
                this.bodyAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ApartmentAddress {
            get {
                return this.apartmentAddressField;
            }
            set {
                this.apartmentAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class HistoriUlFace {
        
        private System.Nullable<System.DateTime> dateNoStartField;
        
        private bool dateNoStartFieldSpecified;
        
        private System.Nullable<System.DateTime> dateNoFinishField;
        
        private bool dateNoFinishFieldSpecified;
        
        private int kodeNoField;
        
        private bool kodeNoFieldSpecified;
        
        private string kppField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateNoStart {
            get {
                return this.dateNoStartField;
            }
            set {
                this.dateNoStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateNoStartSpecified {
            get {
                return this.dateNoStartFieldSpecified;
            }
            set {
                this.dateNoStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateNoFinish {
            get {
                return this.dateNoFinishField;
            }
            set {
                this.dateNoFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateNoFinishSpecified {
            get {
                return this.dateNoFinishFieldSpecified;
            }
            set {
                this.dateNoFinishFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int KodeNo {
            get {
                return this.kodeNoField;
            }
            set {
                this.kodeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KodeNoSpecified {
            get {
                return this.kodeNoFieldSpecified;
            }
            set {
                this.kodeNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CashUlFace {
        
        private System.Nullable<System.DateTime> dataOpenCashField;
        
        private System.Nullable<System.DateTime> dataClosedCashField;
        
        private string nameFullField;
        
        private string cashNumberField;
        
        private string typeCashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataOpenCash {
            get {
                return this.dataOpenCashField;
            }
            set {
                this.dataOpenCashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataClosedCash {
            get {
                return this.dataClosedCashField;
            }
            set {
                this.dataClosedCashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFull {
            get {
                return this.nameFullField;
            }
            set {
                this.nameFullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CashNumber {
            get {
                return this.cashNumberField;
            }
            set {
                this.cashNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeCash {
            get {
                return this.typeCashField;
            }
            set {
                this.typeCashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CashBankSpr {
        
        private System.Nullable<System.DateTime> dateWayField;
        
        private System.Nullable<System.DateTime> datePriemField;
        
        private string nameBankField;
        
        private string numberCashField;
        
        private string dostavkaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateWay {
            get {
                return this.dateWayField;
            }
            set {
                this.dateWayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DatePriem {
            get {
                return this.datePriemField;
            }
            set {
                this.datePriemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameBank {
            get {
                return this.nameBankField;
            }
            set {
                this.nameBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumberCash {
            get {
                return this.numberCashField;
            }
            set {
                this.numberCashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Dostavka {
            get {
                return this.dostavkaField;
            }
            set {
                this.dostavkaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RukAndUcrh {
        
        private TypeObject[] typeObjectField;
        
        private int idFlField;
        
        private bool idFlFieldSpecified;
        
        private int idUlField;
        
        private bool idUlFieldSpecified;
        
        private string nameFlField;
        
        private string innField;
        
        private string priznakField;
        
        private string dateStartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TypeObject")]
        public TypeObject[] TypeObject {
            get {
                return this.typeObjectField;
            }
            set {
                this.typeObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdFl {
            get {
                return this.idFlField;
            }
            set {
                this.idFlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdFlSpecified {
            get {
                return this.idFlFieldSpecified;
            }
            set {
                this.idFlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUl {
            get {
                return this.idUlField;
            }
            set {
                this.idUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUlSpecified {
            get {
                return this.idUlFieldSpecified;
            }
            set {
                this.idUlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFl {
            get {
                return this.nameFlField;
            }
            set {
                this.nameFlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Priznak {
            get {
                return this.priznakField;
            }
            set {
                this.priznakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TypeObject {
        
        private ImZmTrFl[] imZmTrFlField;
        
        private string typeObject1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImZmTrFl")]
        public ImZmTrFl[] ImZmTrFl {
            get {
                return this.imZmTrFlField;
            }
            set {
                this.imZmTrFlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("TypeObject")]
        public string TypeObject1 {
            get {
                return this.typeObject1Field;
            }
            set {
                this.typeObject1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ImZmTrFl {
        
        private string nameObjectField;
        
        private string addresObjectField;
        
        private string dateStartField;
        
        private string dateFinishField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameObject {
            get {
                return this.nameObjectField;
            }
            set {
                this.nameObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AddresObject {
            get {
                return this.addresObjectField;
            }
            set {
                this.addresObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateFinish {
            get {
                return this.dateFinishField;
            }
            set {
                this.dateFinishField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ImZmTrUl {
        
        private System.Nullable<System.DateTime> dateFactStartField;
        
        private System.Nullable<System.DateTime> dateFactFinishField;
        
        private string typeObjectField;
        
        private string nameObjectField;
        
        private string addresObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFactStart {
            get {
                return this.dateFactStartField;
            }
            set {
                this.dateFactStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFactFinish {
            get {
                return this.dateFactFinishField;
            }
            set {
                this.dateFactFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeObject {
            get {
                return this.typeObjectField;
            }
            set {
                this.typeObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameObject {
            get {
                return this.nameObjectField;
            }
            set {
                this.nameObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AddresObject {
            get {
                return this.addresObjectField;
            }
            set {
                this.addresObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Active {
        
        private System.Nullable<decimal> god1Field;
        
        private System.Nullable<decimal> god2Field;
        
        private System.Nullable<decimal> god3Field;
        
        private string nameParametrField;
        
        public Active() {
            this.god1Field = ((decimal)(0m));
            this.god2Field = ((decimal)(0m));
            this.god3Field = ((decimal)(0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God1 {
            get {
                return this.god1Field;
            }
            set {
                this.god1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God2 {
            get {
                return this.god2Field;
            }
            set {
                this.god2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God3 {
            get {
                return this.god3Field;
            }
            set {
                this.god3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameParametr {
            get {
                return this.nameParametrField;
            }
            set {
                this.nameParametrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Balans {
        
        private System.Nullable<decimal> god1Field;
        
        private bool god1FieldSpecified;
        
        private System.Nullable<decimal> god2Field;
        
        private bool god2FieldSpecified;
        
        private System.Nullable<decimal> god3Field;
        
        private bool god3FieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameParametrField;
        
        private string codeParametrField;
        
        public Balans() {
            this.god1Field = ((decimal)(0m));
            this.god2Field = ((decimal)(0m));
            this.god3Field = ((decimal)(0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God1 {
            get {
                return this.god1Field;
            }
            set {
                this.god1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool God1Specified {
            get {
                return this.god1FieldSpecified;
            }
            set {
                this.god1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God2 {
            get {
                return this.god2Field;
            }
            set {
                this.god2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool God2Specified {
            get {
                return this.god2FieldSpecified;
            }
            set {
                this.god2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God3 {
            get {
                return this.god3Field;
            }
            set {
                this.god3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool God3Specified {
            get {
                return this.god3FieldSpecified;
            }
            set {
                this.god3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameParametr {
            get {
                return this.nameParametrField;
            }
            set {
                this.nameParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeParametr {
            get {
                return this.codeParametrField;
            }
            set {
                this.codeParametrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Profit {
        
        private System.Nullable<decimal> god1Field;
        
        private bool god1FieldSpecified;
        
        private System.Nullable<decimal> god2Field;
        
        private bool god2FieldSpecified;
        
        private System.Nullable<decimal> god3Field;
        
        private bool god3FieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameParametrField;
        
        private string codeParametrField;
        
        public Profit() {
            this.god1Field = ((decimal)(0m));
            this.god2Field = ((decimal)(0m));
            this.god3Field = ((decimal)(0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God1 {
            get {
                return this.god1Field;
            }
            set {
                this.god1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool God1Specified {
            get {
                return this.god1FieldSpecified;
            }
            set {
                this.god1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God2 {
            get {
                return this.god2Field;
            }
            set {
                this.god2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool God2Specified {
            get {
                return this.god2FieldSpecified;
            }
            set {
                this.god2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> God3 {
            get {
                return this.god3Field;
            }
            set {
                this.god3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool God3Specified {
            get {
                return this.god3FieldSpecified;
            }
            set {
                this.god3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameParametr {
            get {
                return this.nameParametrField;
            }
            set {
                this.nameParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeParametr {
            get {
                return this.codeParametrField;
            }
            set {
                this.codeParametrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Nds {
        
        private decimal summField;
        
        private decimal summOutField;
        
        private decimal summNalogField;
        
        private decimal summInField;
        
        private long regNumDeclField;
        
        private bool regNumDeclFieldSpecified;
        
        private int godField;
        
        private bool godFieldSpecified;
        
        private string periodField;
        
        /// <remarks/>
        public decimal Summ {
            get {
                return this.summField;
            }
            set {
                this.summField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummOut {
            get {
                return this.summOutField;
            }
            set {
                this.summOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummNalog {
            get {
                return this.summNalogField;
            }
            set {
                this.summNalogField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummIn {
            get {
                return this.summInField;
            }
            set {
                this.summInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long RegNumDecl {
            get {
                return this.regNumDeclField;
            }
            set {
                this.regNumDeclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegNumDeclSpecified {
            get {
                return this.regNumDeclFieldSpecified;
            }
            set {
                this.regNumDeclFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int God {
            get {
                return this.godField;
            }
            set {
                this.godField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GodSpecified {
            get {
                return this.godFieldSpecified;
            }
            set {
                this.godFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FlRukUcrh {
        
        private string nameFlField;
        
        private string innField;
        
        private string priznakField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFl {
            get {
                return this.nameFlField;
            }
            set {
                this.nameFlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Priznak {
            get {
                return this.priznakField;
            }
            set {
                this.priznakField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SummaryBankSales {
        
        private int idField;
        
        private string nameField;
        
        private string innField;
        
        private string kppField;
        
        private decimal yearBookSalesSumm1Field;
        
        private decimal yearCashBankSumm1Field;
        
        private decimal yearBookSalesSumm2Field;
        
        private decimal yearCashBankSumm2Field;
        
        private decimal yearBookSalesSumm3Field;
        
        private decimal yearCashBankSumm3Field;
        
        private decimal yearBookSalesSumm4Field;
        
        private decimal yearCashBankSumm4Field;
        
        public SummaryBankSales() {
            this.yearBookSalesSumm1Field = ((decimal)(0.00m));
            this.yearCashBankSumm1Field = ((decimal)(0.00m));
            this.yearBookSalesSumm2Field = ((decimal)(0.00m));
            this.yearCashBankSumm2Field = ((decimal)(0.00m));
            this.yearBookSalesSumm3Field = ((decimal)(0.00m));
            this.yearCashBankSumm3Field = ((decimal)(0.00m));
            this.yearBookSalesSumm4Field = ((decimal)(0.00m));
            this.yearCashBankSumm4Field = ((decimal)(0.00m));
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm1 {
            get {
                return this.yearBookSalesSumm1Field;
            }
            set {
                this.yearBookSalesSumm1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm1 {
            get {
                return this.yearCashBankSumm1Field;
            }
            set {
                this.yearCashBankSumm1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm2 {
            get {
                return this.yearBookSalesSumm2Field;
            }
            set {
                this.yearBookSalesSumm2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm2 {
            get {
                return this.yearCashBankSumm2Field;
            }
            set {
                this.yearCashBankSumm2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm3 {
            get {
                return this.yearBookSalesSumm3Field;
            }
            set {
                this.yearBookSalesSumm3Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm3 {
            get {
                return this.yearCashBankSumm3Field;
            }
            set {
                this.yearCashBankSumm3Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm4 {
            get {
                return this.yearBookSalesSumm4Field;
            }
            set {
                this.yearBookSalesSumm4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm4 {
            get {
                return this.yearCashBankSumm4Field;
            }
            set {
                this.yearCashBankSumm4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SummaryBankPurchase {
        
        private int idField;
        
        private string innField;
        
        private string kppField;
        
        private string nameField;
        
        private decimal yearBookSalesSumm1Field;
        
        private decimal yearCashBankSumm1Field;
        
        private decimal yearBookSalesSumm2Field;
        
        private decimal yearCashBankSumm2Field;
        
        private decimal yearBookSalesSumm3Field;
        
        private decimal yearCashBankSumm3Field;
        
        private decimal yearBookSalesSumm4Field;
        
        private decimal yearCashBankSumm4Field;
        
        public SummaryBankPurchase() {
            this.yearBookSalesSumm1Field = ((decimal)(0.00m));
            this.yearCashBankSumm1Field = ((decimal)(0.00m));
            this.yearBookSalesSumm2Field = ((decimal)(0.00m));
            this.yearCashBankSumm2Field = ((decimal)(0.00m));
            this.yearBookSalesSumm3Field = ((decimal)(0.00m));
            this.yearCashBankSumm3Field = ((decimal)(0.00m));
            this.yearBookSalesSumm4Field = ((decimal)(0.00m));
            this.yearCashBankSumm4Field = ((decimal)(0.00m));
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm1 {
            get {
                return this.yearBookSalesSumm1Field;
            }
            set {
                this.yearBookSalesSumm1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm1 {
            get {
                return this.yearCashBankSumm1Field;
            }
            set {
                this.yearCashBankSumm1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm2 {
            get {
                return this.yearBookSalesSumm2Field;
            }
            set {
                this.yearBookSalesSumm2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm2 {
            get {
                return this.yearCashBankSumm2Field;
            }
            set {
                this.yearCashBankSumm2Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm3 {
            get {
                return this.yearBookSalesSumm3Field;
            }
            set {
                this.yearBookSalesSumm3Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm3 {
            get {
                return this.yearCashBankSumm3Field;
            }
            set {
                this.yearCashBankSumm3Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearBookSalesSumm4 {
            get {
                return this.yearBookSalesSumm4Field;
            }
            set {
                this.yearBookSalesSumm4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal YearCashBankSumm4 {
            get {
                return this.yearCashBankSumm4Field;
            }
            set {
                this.yearCashBankSumm4Field = value;
            }
        }
    }
}
