//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2053.0.
// 
namespace EfDatabaseAutomation.Automation.BaseLogica.AutoLogicInventory.ModelReportContainer {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ReportDocumentContainer {
        
        private ReportContainer reportContainerField;
        
        /// <remarks/>
        public ReportContainer ReportContainer {
            get {
                return this.reportContainerField;
            }
            set {
                this.reportContainerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ReportContainer {
        
        private ModelReport[] modelReportField;
        
        private int idContainerField;
        
        private string barcodeContainerField;
        
        private int countCurrentField;
        
        private int countDocumentMinField;
        
        private int countDocumentMaxField;
        
        private int countDocField;
        
        private bool isFinishContainerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModelReport")]
        public ModelReport[] ModelReport {
            get {
                return this.modelReportField;
            }
            set {
                this.modelReportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdContainer {
            get {
                return this.idContainerField;
            }
            set {
                this.idContainerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BarcodeContainer {
            get {
                return this.barcodeContainerField;
            }
            set {
                this.barcodeContainerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CountCurrent {
            get {
                return this.countCurrentField;
            }
            set {
                this.countCurrentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CountDocumentMin {
            get {
                return this.countDocumentMinField;
            }
            set {
                this.countDocumentMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CountDocumentMax {
            get {
                return this.countDocumentMaxField;
            }
            set {
                this.countDocumentMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int CountDoc {
            get {
                return this.countDocField;
            }
            set {
                this.countDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsFinishContainer {
            get {
                return this.isFinishContainerField;
            }
            set {
                this.isFinishContainerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ModelReport {
        
        private DocumentInventory[] documentInventoryField;
        
        private int idContainerField;
        
        private long numberOgrnGrnField;
        
        private int sumPageIncludedField;
        
        private int sumPageNotIncludedField;
        
        private int stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentInventory")]
        public DocumentInventory[] DocumentInventory {
            get {
                return this.documentInventoryField;
            }
            set {
                this.documentInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdContainer {
            get {
                return this.idContainerField;
            }
            set {
                this.idContainerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NumberOgrnGrn {
            get {
                return this.numberOgrnGrnField;
            }
            set {
                this.numberOgrnGrnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SumPageIncluded {
            get {
                return this.sumPageIncludedField;
            }
            set {
                this.sumPageIncludedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SumPageNotIncluded {
            get {
                return this.sumPageNotIncludedField;
            }
            set {
                this.sumPageNotIncludedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DocumentInventory {
        
        private string guidDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GuidDocument {
            get {
                return this.guidDocumentField;
            }
            set {
                this.guidDocumentField = value;
            }
        }
    }
}
