//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabaseAutomation.Automation.BaseLogica.SqlSelect.XsdDTOSheme {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DataBaseUlSelect {
        
        private UlFace[] ulFaceField;
        
        private DeclarationUl[] declarationUlField;
        
        private DeclarationData declarationDataField;
        
        private RukAndUch rukAndUchField;
        
        private Nds ndsField;
        
        private Profit profitField;
        
        private Balans balansField;
        
        private UlCommunication ulCommunicationField;
        
        private ObjectFace[] objectFaceField;
        
        private CashUlFace[] cashUlFaceField;
        
        private StatementUcr[] statementUcrField;
        
        private HeadingStatement[][] statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UlFace")]
        public UlFace[] UlFace {
            get {
                return this.ulFaceField;
            }
            set {
                this.ulFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeclarationUl")]
        public DeclarationUl[] DeclarationUl {
            get {
                return this.declarationUlField;
            }
            set {
                this.declarationUlField = value;
            }
        }
        
        /// <remarks/>
        public DeclarationData DeclarationData {
            get {
                return this.declarationDataField;
            }
            set {
                this.declarationDataField = value;
            }
        }
        
        /// <remarks/>
        public RukAndUch RukAndUch {
            get {
                return this.rukAndUchField;
            }
            set {
                this.rukAndUchField = value;
            }
        }
        
        /// <remarks/>
        public Nds Nds {
            get {
                return this.ndsField;
            }
            set {
                this.ndsField = value;
            }
        }
        
        /// <remarks/>
        public Profit Profit {
            get {
                return this.profitField;
            }
            set {
                this.profitField = value;
            }
        }
        
        /// <remarks/>
        public Balans Balans {
            get {
                return this.balansField;
            }
            set {
                this.balansField = value;
            }
        }
        
        /// <remarks/>
        public UlCommunication UlCommunication {
            get {
                return this.ulCommunicationField;
            }
            set {
                this.ulCommunicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectFace")]
        public ObjectFace[] ObjectFace {
            get {
                return this.objectFaceField;
            }
            set {
                this.objectFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CashUlFace")]
        public CashUlFace[] CashUlFace {
            get {
                return this.cashUlFaceField;
            }
            set {
                this.cashUlFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatementUcr")]
        public StatementUcr[] StatementUcr {
            get {
                return this.statementUcrField;
            }
            set {
                this.statementUcrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HeadingStatement", typeof(HeadingStatement), IsNullable=false)]
        public HeadingStatement[][] Statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UlFace {
        
        private string logicsButtonField;
        
        private System.Nullable<System.DateTime> dateOgrnField;
        
        private System.Nullable<long> fidField;
        
        private System.Nullable<long> idNumField;
        
        private string innField;
        
        private string nameFullField;
        
        private string kppField;
        
        private string ogrnField;
        
        private string statusUlField;
        
        private string nameSmallField;
        
        private string addressField;
        
        private string statusFullField;
        
        public UlFace() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateOgrn {
            get {
                return this.dateOgrnField;
            }
            set {
                this.dateOgrnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Fid {
            get {
                return this.fidField;
            }
            set {
                this.fidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdNum {
            get {
                return this.idNumField;
            }
            set {
                this.idNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFull {
            get {
                return this.nameFullField;
            }
            set {
                this.nameFullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ogrn {
            get {
                return this.ogrnField;
            }
            set {
                this.ogrnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusUl {
            get {
                return this.statusUlField;
            }
            set {
                this.statusUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameSmall {
            get {
                return this.nameSmallField;
            }
            set {
                this.nameSmallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusFull {
            get {
                return this.statusFullField;
            }
            set {
                this.statusFullField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DeclarationUl {
        
        private string logicsButtonField;
        
        private long regNumDeclField;
        
        private double psummField;
        
        private int numberKorField;
        
        private int godField;
        
        private string nameDocumentField;
        
        private string vidDocField;
        
        private string periodField;
        
        private string kndField;
        
        public DeclarationUl() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        public long RegNumDecl {
            get {
                return this.regNumDeclField;
            }
            set {
                this.regNumDeclField = value;
            }
        }
        
        /// <remarks/>
        public double Psumm {
            get {
                return this.psummField;
            }
            set {
                this.psummField = value;
            }
        }
        
        /// <remarks/>
        public int NumberKor {
            get {
                return this.numberKorField;
            }
            set {
                this.numberKorField = value;
            }
        }
        
        /// <remarks/>
        public int God {
            get {
                return this.godField;
            }
            set {
                this.godField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameDocument {
            get {
                return this.nameDocumentField;
            }
            set {
                this.nameDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VidDoc {
            get {
                return this.vidDocField;
            }
            set {
                this.vidDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Knd {
            get {
                return this.kndField;
            }
            set {
                this.kndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DeclarationData {
        
        private long regNumDeclField;
        
        private string codeStringField;
        
        private string nameParametrField;
        
        private string codeParametrField;
        
        private string dataFaceField;
        
        private string dataInspectorField;
        
        private string errorField;
        
        /// <remarks/>
        public long RegNumDecl {
            get {
                return this.regNumDeclField;
            }
            set {
                this.regNumDeclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeString {
            get {
                return this.codeStringField;
            }
            set {
                this.codeStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameParametr {
            get {
                return this.nameParametrField;
            }
            set {
                this.nameParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeParametr {
            get {
                return this.codeParametrField;
            }
            set {
                this.codeParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataFace {
            get {
                return this.dataFaceField;
            }
            set {
                this.dataFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataInspector {
            get {
                return this.dataInspectorField;
            }
            set {
                this.dataInspectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RukAndUch {
        
        private System.Nullable<System.DateTime> dateStartField;
        
        private System.Nullable<System.DateTime> dateFinishField;
        
        private string logicsButtonField;
        
        private string priznakCardField;
        
        private string nameFlField;
        
        private string innField;
        
        private string priznakField;
        
        public RukAndUch() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFinish {
            get {
                return this.dateFinishField;
            }
            set {
                this.dateFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PriznakCard {
            get {
                return this.priznakCardField;
            }
            set {
                this.priznakCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFl {
            get {
                return this.nameFlField;
            }
            set {
                this.nameFlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Priznak {
            get {
                return this.priznakField;
            }
            set {
                this.priznakField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Nds {
        
        private long regNumDeclField;
        
        private int numberKorField;
        
        private int godField;
        
        private decimal summField;
        
        private decimal summOutField;
        
        private decimal summNalogField;
        
        private decimal summInField;
        
        private string logicsButtonField;
        
        private string vidDocField;
        
        private string periodField;
        
        public Nds() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public long RegNumDecl {
            get {
                return this.regNumDeclField;
            }
            set {
                this.regNumDeclField = value;
            }
        }
        
        /// <remarks/>
        public int NumberKor {
            get {
                return this.numberKorField;
            }
            set {
                this.numberKorField = value;
            }
        }
        
        /// <remarks/>
        public int God {
            get {
                return this.godField;
            }
            set {
                this.godField = value;
            }
        }
        
        /// <remarks/>
        public decimal Summ {
            get {
                return this.summField;
            }
            set {
                this.summField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummOut {
            get {
                return this.summOutField;
            }
            set {
                this.summOutField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummNalog {
            get {
                return this.summNalogField;
            }
            set {
                this.summNalogField = value;
            }
        }
        
        /// <remarks/>
        public decimal SummIn {
            get {
                return this.summInField;
            }
            set {
                this.summInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VidDoc {
            get {
                return this.vidDocField;
            }
            set {
                this.vidDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Profit {
        
        private long regNumDeclField;
        
        private int numberKorField;
        
        private int godField;
        
        private long par2_010Field;
        
        private long par2_020Field;
        
        private long par2_030Field;
        
        private long par2_040Field;
        
        private long par2_050Field;
        
        private long par2_060Field;
        
        private long par2_070Field;
        
        private string logicsButtonField;
        
        private string nameDocumentField;
        
        private string vidDocField;
        
        private string periodField;
        
        public Profit() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public long RegNumDecl {
            get {
                return this.regNumDeclField;
            }
            set {
                this.regNumDeclField = value;
            }
        }
        
        /// <remarks/>
        public int NumberKor {
            get {
                return this.numberKorField;
            }
            set {
                this.numberKorField = value;
            }
        }
        
        /// <remarks/>
        public int God {
            get {
                return this.godField;
            }
            set {
                this.godField = value;
            }
        }
        
        /// <remarks/>
        public long Par2_010 {
            get {
                return this.par2_010Field;
            }
            set {
                this.par2_010Field = value;
            }
        }
        
        /// <remarks/>
        public long Par2_020 {
            get {
                return this.par2_020Field;
            }
            set {
                this.par2_020Field = value;
            }
        }
        
        /// <remarks/>
        public long Par2_030 {
            get {
                return this.par2_030Field;
            }
            set {
                this.par2_030Field = value;
            }
        }
        
        /// <remarks/>
        public long Par2_040 {
            get {
                return this.par2_040Field;
            }
            set {
                this.par2_040Field = value;
            }
        }
        
        /// <remarks/>
        public long Par2_050 {
            get {
                return this.par2_050Field;
            }
            set {
                this.par2_050Field = value;
            }
        }
        
        /// <remarks/>
        public long Par2_060 {
            get {
                return this.par2_060Field;
            }
            set {
                this.par2_060Field = value;
            }
        }
        
        /// <remarks/>
        public long Par2_070 {
            get {
                return this.par2_070Field;
            }
            set {
                this.par2_070Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameDocument {
            get {
                return this.nameDocumentField;
            }
            set {
                this.nameDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VidDoc {
            get {
                return this.vidDocField;
            }
            set {
                this.vidDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Balans {
        
        private long regNumDeclField;
        
        private string logicsButtonField;
        
        private int numberKorField;
        
        private int godField;
        
        private decimal par2110_4Field;
        
        private decimal par2120_4Field;
        
        private decimal par2100_4Field;
        
        private decimal par2210_4Field;
        
        private decimal par2220_4Field;
        
        private decimal par2200_4Field;
        
        private decimal par2320_4Field;
        
        private decimal par2330_4Field;
        
        private decimal par2310_4Field;
        
        private decimal par2340_4Field;
        
        private decimal par2350_4Field;
        
        private decimal par2300_4Field;
        
        private decimal par2450_4Field;
        
        private decimal par2430_4Field;
        
        private decimal par2410_4Field;
        
        private decimal par2400_4Field;
        
        private string nameDocumentField;
        
        private string vidDocField;
        
        private string periodField;
        
        public Balans() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        public long RegNumDecl {
            get {
                return this.regNumDeclField;
            }
            set {
                this.regNumDeclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        public int NumberKor {
            get {
                return this.numberKorField;
            }
            set {
                this.numberKorField = value;
            }
        }
        
        /// <remarks/>
        public int God {
            get {
                return this.godField;
            }
            set {
                this.godField = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2110_4 {
            get {
                return this.par2110_4Field;
            }
            set {
                this.par2110_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2120_4 {
            get {
                return this.par2120_4Field;
            }
            set {
                this.par2120_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2100_4 {
            get {
                return this.par2100_4Field;
            }
            set {
                this.par2100_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2210_4 {
            get {
                return this.par2210_4Field;
            }
            set {
                this.par2210_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2220_4 {
            get {
                return this.par2220_4Field;
            }
            set {
                this.par2220_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2200_4 {
            get {
                return this.par2200_4Field;
            }
            set {
                this.par2200_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2320_4 {
            get {
                return this.par2320_4Field;
            }
            set {
                this.par2320_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2330_4 {
            get {
                return this.par2330_4Field;
            }
            set {
                this.par2330_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2310_4 {
            get {
                return this.par2310_4Field;
            }
            set {
                this.par2310_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2340_4 {
            get {
                return this.par2340_4Field;
            }
            set {
                this.par2340_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2350_4 {
            get {
                return this.par2350_4Field;
            }
            set {
                this.par2350_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2300_4 {
            get {
                return this.par2300_4Field;
            }
            set {
                this.par2300_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2450_4 {
            get {
                return this.par2450_4Field;
            }
            set {
                this.par2450_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2430_4 {
            get {
                return this.par2430_4Field;
            }
            set {
                this.par2430_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2410_4 {
            get {
                return this.par2410_4Field;
            }
            set {
                this.par2410_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par2400_4 {
            get {
                return this.par2400_4Field;
            }
            set {
                this.par2400_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameDocument {
            get {
                return this.nameDocumentField;
            }
            set {
                this.nameDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VidDoc {
            get {
                return this.vidDocField;
            }
            set {
                this.vidDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UlCommunication {
        
        private System.Nullable<System.DateTime> dateOgrnField;
        
        private int idUlField;
        
        private string innField;
        
        private string nameFullField;
        
        private string kppField;
        
        private string ogrnField;
        
        private string statusUlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateOgrn {
            get {
                return this.dateOgrnField;
            }
            set {
                this.dateOgrnField = value;
            }
        }
        
        /// <remarks/>
        public int IdUl {
            get {
                return this.idUlField;
            }
            set {
                this.idUlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFull {
            get {
                return this.nameFullField;
            }
            set {
                this.nameFullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ogrn {
            get {
                return this.ogrnField;
            }
            set {
                this.ogrnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StatusUl {
            get {
                return this.statusUlField;
            }
            set {
                this.statusUlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ObjectFace {
        
        private System.Nullable<System.DateTime> dateStartField;
        
        private System.Nullable<System.DateTime> dateFinishField;
        
        private string nameFaceField;
        
        private string innFaceField;
        
        private string nameObjectField;
        
        private string reasonSettingStartField;
        
        private string reasonSettingFinishField;
        
        private string addresObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFinish {
            get {
                return this.dateFinishField;
            }
            set {
                this.dateFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFace {
            get {
                return this.nameFaceField;
            }
            set {
                this.nameFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InnFace {
            get {
                return this.innFaceField;
            }
            set {
                this.innFaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameObject {
            get {
                return this.nameObjectField;
            }
            set {
                this.nameObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonSettingStart {
            get {
                return this.reasonSettingStartField;
            }
            set {
                this.reasonSettingStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReasonSettingFinish {
            get {
                return this.reasonSettingFinishField;
            }
            set {
                this.reasonSettingFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AddresObject {
            get {
                return this.addresObjectField;
            }
            set {
                this.addresObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CashUlFace {
        
        private System.Nullable<long> idNumField;
        
        private System.Nullable<System.DateTime> dataOpenCashField;
        
        private System.Nullable<System.DateTime> dataClosedCashField;
        
        private string nameFullField;
        
        private string cashNumberField;
        
        private string typeCashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdNum {
            get {
                return this.idNumField;
            }
            set {
                this.idNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataOpenCash {
            get {
                return this.dataOpenCashField;
            }
            set {
                this.dataOpenCashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataClosedCash {
            get {
                return this.dataClosedCashField;
            }
            set {
                this.dataClosedCashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFull {
            get {
                return this.nameFullField;
            }
            set {
                this.nameFullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CashNumber {
            get {
                return this.cashNumberField;
            }
            set {
                this.cashNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeCash {
            get {
                return this.typeCashField;
            }
            set {
                this.typeCashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StatementUcr {
        
        private string logicsButtonField;
        
        private System.Nullable<System.DateTime> dateStartField;
        
        private System.Nullable<System.DateTime> dateFinishField;
        
        private string nameField;
        
        private string priznakField;
        
        private string innField;
        
        public StatementUcr() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateStart {
            get {
                return this.dateStartField;
            }
            set {
                this.dateStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateFinish {
            get {
                return this.dateFinishField;
            }
            set {
                this.dateFinishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Priznak {
            get {
                return this.priznakField;
            }
            set {
                this.priznakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class HeadingStatement {
        
        private StatementFull[] statementFullField;
        
        private string nameIndexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatementFull")]
        public StatementFull[] StatementFull {
            get {
                return this.statementFullField;
            }
            set {
                this.statementFullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameIndex {
            get {
                return this.nameIndexField;
            }
            set {
                this.nameIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StatementFull {
        
        private int varIndexField;
        
        private string nameParametrField;
        
        private string valuesStatementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int VarIndex {
            get {
                return this.varIndexField;
            }
            set {
                this.varIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameParametr {
            get {
                return this.nameParametrField;
            }
            set {
                this.nameParametrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValuesStatement {
            get {
                return this.valuesStatementField;
            }
            set {
                this.valuesStatementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Active {
        
        private string logicsButtonField;
        
        private long regNumDeclField;
        
        private int numberKorField;
        
        private int godField;
        
        private decimal par1110_6Field;
        
        private decimal par1110_5Field;
        
        private decimal par1110_4Field;
        
        private decimal par1150_6Field;
        
        private decimal par1150_5Field;
        
        private decimal par1150_4Field;
        
        private decimal par1160_6Field;
        
        private decimal par1160_5Field;
        
        private decimal par1160_4Field;
        
        private decimal par1170_6Field;
        
        private decimal par1170_5Field;
        
        private decimal par1170_4Field;
        
        private decimal par1210_6Field;
        
        private decimal par1210_5Field;
        
        private decimal par1210_4Field;
        
        private decimal par1230_6Field;
        
        private decimal par1230_5Field;
        
        private decimal par1230_4Field;
        
        private decimal par1240_6Field;
        
        private decimal par1240_5Field;
        
        private decimal par1240_4Field;
        
        private decimal par1250_6Field;
        
        private decimal par1250_5Field;
        
        private decimal par1250_4Field;
        
        private decimal par1260_6Field;
        
        private decimal par1260_5Field;
        
        private decimal par1260_4Field;
        
        private decimal par1410_6Field;
        
        private decimal par1410_5Field;
        
        private decimal par1410_4Field;
        
        private decimal par1420_6Field;
        
        private decimal par1420_5Field;
        
        private decimal par1420_4Field;
        
        private decimal par1450_6Field;
        
        private decimal par1450_5Field;
        
        private decimal par1450_4Field;
        
        private decimal par1510_6Field;
        
        private decimal par1510_5Field;
        
        private decimal par1510_4Field;
        
        private decimal par1520_6Field;
        
        private decimal par1520_5Field;
        
        private decimal par1520_4Field;
        
        private string nameDocumentField;
        
        private string vidDocField;
        
        private string periodField;
        
        public Active() {
            this.logicsButtonField = "Button";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogicsButton {
            get {
                return this.logicsButtonField;
            }
            set {
                this.logicsButtonField = value;
            }
        }
        
        /// <remarks/>
        public long RegNumDecl {
            get {
                return this.regNumDeclField;
            }
            set {
                this.regNumDeclField = value;
            }
        }
        
        /// <remarks/>
        public int NumberKor {
            get {
                return this.numberKorField;
            }
            set {
                this.numberKorField = value;
            }
        }
        
        /// <remarks/>
        public int God {
            get {
                return this.godField;
            }
            set {
                this.godField = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1110_6 {
            get {
                return this.par1110_6Field;
            }
            set {
                this.par1110_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1110_5 {
            get {
                return this.par1110_5Field;
            }
            set {
                this.par1110_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1110_4 {
            get {
                return this.par1110_4Field;
            }
            set {
                this.par1110_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1150_6 {
            get {
                return this.par1150_6Field;
            }
            set {
                this.par1150_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1150_5 {
            get {
                return this.par1150_5Field;
            }
            set {
                this.par1150_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1150_4 {
            get {
                return this.par1150_4Field;
            }
            set {
                this.par1150_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1160_6 {
            get {
                return this.par1160_6Field;
            }
            set {
                this.par1160_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1160_5 {
            get {
                return this.par1160_5Field;
            }
            set {
                this.par1160_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1160_4 {
            get {
                return this.par1160_4Field;
            }
            set {
                this.par1160_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1170_6 {
            get {
                return this.par1170_6Field;
            }
            set {
                this.par1170_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1170_5 {
            get {
                return this.par1170_5Field;
            }
            set {
                this.par1170_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1170_4 {
            get {
                return this.par1170_4Field;
            }
            set {
                this.par1170_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1210_6 {
            get {
                return this.par1210_6Field;
            }
            set {
                this.par1210_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1210_5 {
            get {
                return this.par1210_5Field;
            }
            set {
                this.par1210_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1210_4 {
            get {
                return this.par1210_4Field;
            }
            set {
                this.par1210_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1230_6 {
            get {
                return this.par1230_6Field;
            }
            set {
                this.par1230_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1230_5 {
            get {
                return this.par1230_5Field;
            }
            set {
                this.par1230_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1230_4 {
            get {
                return this.par1230_4Field;
            }
            set {
                this.par1230_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1240_6 {
            get {
                return this.par1240_6Field;
            }
            set {
                this.par1240_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1240_5 {
            get {
                return this.par1240_5Field;
            }
            set {
                this.par1240_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1240_4 {
            get {
                return this.par1240_4Field;
            }
            set {
                this.par1240_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1250_6 {
            get {
                return this.par1250_6Field;
            }
            set {
                this.par1250_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1250_5 {
            get {
                return this.par1250_5Field;
            }
            set {
                this.par1250_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1250_4 {
            get {
                return this.par1250_4Field;
            }
            set {
                this.par1250_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1260_6 {
            get {
                return this.par1260_6Field;
            }
            set {
                this.par1260_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1260_5 {
            get {
                return this.par1260_5Field;
            }
            set {
                this.par1260_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1260_4 {
            get {
                return this.par1260_4Field;
            }
            set {
                this.par1260_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1410_6 {
            get {
                return this.par1410_6Field;
            }
            set {
                this.par1410_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1410_5 {
            get {
                return this.par1410_5Field;
            }
            set {
                this.par1410_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1410_4 {
            get {
                return this.par1410_4Field;
            }
            set {
                this.par1410_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1420_6 {
            get {
                return this.par1420_6Field;
            }
            set {
                this.par1420_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1420_5 {
            get {
                return this.par1420_5Field;
            }
            set {
                this.par1420_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1420_4 {
            get {
                return this.par1420_4Field;
            }
            set {
                this.par1420_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1450_6 {
            get {
                return this.par1450_6Field;
            }
            set {
                this.par1450_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1450_5 {
            get {
                return this.par1450_5Field;
            }
            set {
                this.par1450_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1450_4 {
            get {
                return this.par1450_4Field;
            }
            set {
                this.par1450_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1510_6 {
            get {
                return this.par1510_6Field;
            }
            set {
                this.par1510_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1510_5 {
            get {
                return this.par1510_5Field;
            }
            set {
                this.par1510_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1510_4 {
            get {
                return this.par1510_4Field;
            }
            set {
                this.par1510_4Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1520_6 {
            get {
                return this.par1520_6Field;
            }
            set {
                this.par1520_6Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1520_5 {
            get {
                return this.par1520_5Field;
            }
            set {
                this.par1520_5Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Par1520_4 {
            get {
                return this.par1520_4Field;
            }
            set {
                this.par1520_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameDocument {
            get {
                return this.nameDocumentField;
            }
            set {
                this.nameDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VidDoc {
            get {
                return this.vidDocField;
            }
            set {
                this.vidDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Statement {
        
        private HeadingStatement[] headingStatementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HeadingStatement")]
        public HeadingStatement[] HeadingStatement {
            get {
                return this.headingStatementField;
            }
            set {
                this.headingStatementField = value;
            }
        }
    }
}
