//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2053.0.
// 
namespace LibaryXMLAutoInventarization.Model.ModelSelectAll {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AllUsers {
        
        private Users[] usersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Users", IsNullable=true)]
        public Users[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class Users {
        
        private Rules rulesField;
        
        private Otdel otdelField;
        
        private Position positionField;
        
        private int idUserField;
        
        private bool idUserFieldSpecified;
        
        private string nameField;
        
        private int idOtdelField;
        
        private bool idOtdelFieldSpecified;
        
        private int idPositionField;
        
        private bool idPositionFieldSpecified;
        
        private int idRuleField;
        
        private bool idRuleFieldSpecified;
        
        private string tabelNumberField;
        
        private string telephonField;
        
        private string telephonUndegroundField;
        
        private string ipTelephonField;
        
        private string macTelephonField;
        
        private string nameUserField;
        
        private string passwordsField;
        
        private sbyte statusActualField;
        
        private bool statusActualFieldSpecified;
        
        private string idHistoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rules Rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Otdel Otdel {
            get {
                return this.otdelField;
            }
            set {
                this.otdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Position Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUserSpecified {
            get {
                return this.idUserFieldSpecified;
            }
            set {
                this.idUserFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdOtdel {
            get {
                return this.idOtdelField;
            }
            set {
                this.idOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdOtdelSpecified {
            get {
                return this.idOtdelFieldSpecified;
            }
            set {
                this.idOtdelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdPosition {
            get {
                return this.idPositionField;
            }
            set {
                this.idPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdPositionSpecified {
            get {
                return this.idPositionFieldSpecified;
            }
            set {
                this.idPositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdRule {
            get {
                return this.idRuleField;
            }
            set {
                this.idRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdRuleSpecified {
            get {
                return this.idRuleFieldSpecified;
            }
            set {
                this.idRuleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TabelNumber {
            get {
                return this.tabelNumberField;
            }
            set {
                this.tabelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Telephon {
            get {
                return this.telephonField;
            }
            set {
                this.telephonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TelephonUndeground {
            get {
                return this.telephonUndegroundField;
            }
            set {
                this.telephonUndegroundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IpTelephon {
            get {
                return this.ipTelephonField;
            }
            set {
                this.ipTelephonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MacTelephon {
            get {
                return this.macTelephonField;
            }
            set {
                this.macTelephonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameUser {
            get {
                return this.nameUserField;
            }
            set {
                this.nameUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Passwords {
            get {
                return this.passwordsField;
            }
            set {
                this.passwordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte StatusActual {
            get {
                return this.statusActualField;
            }
            set {
                this.statusActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusActualSpecified {
            get {
                return this.statusActualFieldSpecified;
            }
            set {
                this.statusActualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdHistory {
            get {
                return this.idHistoryField;
            }
            set {
                this.idHistoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class Rules {
        
        private int idRuleField;
        
        private bool idRuleFieldSpecified;
        
        private string nameRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdRule {
            get {
                return this.idRuleField;
            }
            set {
                this.idRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdRuleSpecified {
            get {
                return this.idRuleFieldSpecified;
            }
            set {
                this.idRuleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameRules {
            get {
                return this.nameRulesField;
            }
            set {
                this.nameRulesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class Otdel {
        
        private int idOtdelField;
        
        private bool idOtdelFieldSpecified;
        
        private string nameOtdelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdOtdel {
            get {
                return this.idOtdelField;
            }
            set {
                this.idOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdOtdelSpecified {
            get {
                return this.idOtdelFieldSpecified;
            }
            set {
                this.idOtdelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameOtdel {
            get {
                return this.nameOtdelField;
            }
            set {
                this.nameOtdelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class Position {
        
        private int idOtdelField;
        
        private bool idOtdelFieldSpecified;
        
        private string namePositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdOtdel {
            get {
                return this.idOtdelField;
            }
            set {
                this.idOtdelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdOtdelSpecified {
            get {
                return this.idOtdelFieldSpecified;
            }
            set {
                this.idOtdelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NamePosition {
            get {
                return this.namePositionField;
            }
            set {
                this.namePositionField = value;
            }
        }
    }
}
