//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.81.0.
// 
namespace LibaryXMLAutoModelXmlSql.Model.ModelMail {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UseTableTemplateBdk {
        
        private string numerdocumentField;
        
        private int n279Field;
        
        private bool n279FieldSpecified;
        
        private string n280Field;
        
        private string d981Field;
        
        private System.DateTime d85Field;
        
        private bool d85FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Numerdocument {
            get {
                return this.numerdocumentField;
            }
            set {
                this.numerdocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int N279 {
            get {
                return this.n279Field;
            }
            set {
                this.n279Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool N279Specified {
            get {
                return this.n279FieldSpecified;
            }
            set {
                this.n279FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string N280 {
            get {
                return this.n280Field;
            }
            set {
                this.n280Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D981 {
            get {
                return this.d981Field;
            }
            set {
                this.d981Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime D85 {
            get {
                return this.d85Field;
            }
            set {
                this.d85Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool D85Specified {
            get {
                return this.d85FieldSpecified;
            }
            set {
                this.d85FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WordDocument {
        
        private UseTableTemplateBdk[] useTableTemplateBdkField;
        
        private string numerdocumentField;
        
        private int idNamedocumentField;
        
        private bool idNamedocumentFieldSpecified;
        
        private string namefileField;
        
        private System.DateTime dateCreateField;
        
        private bool dateCreateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UseTableTemplateBdk")]
        public UseTableTemplateBdk[] UseTableTemplateBdk {
            get {
                return this.useTableTemplateBdkField;
            }
            set {
                this.useTableTemplateBdkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Numerdocument {
            get {
                return this.numerdocumentField;
            }
            set {
                this.numerdocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdNamedocument {
            get {
                return this.idNamedocumentField;
            }
            set {
                this.idNamedocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdNamedocumentSpecified {
            get {
                return this.idNamedocumentFieldSpecified;
            }
            set {
                this.idNamedocumentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Namefile {
            get {
                return this.namefileField;
            }
            set {
                this.namefileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                this.dateCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCreateSpecified {
            get {
                return this.dateCreateFieldSpecified;
            }
            set {
                this.dateCreateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Mails", Namespace="", IsNullable=false)]
    public partial class Mail {
        
        private WordDocument[] wordDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WordDocument")]
        public WordDocument[] WordDocument {
            get {
                return this.wordDocumentField;
            }
            set {
                this.wordDocumentField = value;
            }
        }
    }
}
