//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.7.2046.0.
// 
namespace EfDatabaseAutomation.Automation.BaseLogica.XsdAuto.ProcedureDeclaration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Declaration {
        
        private DeclarationMemo[] declarationMemoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeclarationMemo", IsNullable=true)]
        public DeclarationMemo[] DeclarationMemo {
            get {
                return this.declarationMemoField;
            }
            set {
                this.declarationMemoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class DeclarationMemo {
        
        private string п0020Field;
        
        private string п0148Field;
        
        private string п0031Field;
        
        private string п0033Field;
        
        private string п0425Field;
        
        private string п0010Field;
        
        private string п0975Field;
        
        private string п0417Field;
        
        private string п0419Field;
        
        private string п0421Field;
        
        private string п0430Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0020 {
            get {
                return this.п0020Field;
            }
            set {
                this.п0020Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0148 {
            get {
                return this.п0148Field;
            }
            set {
                this.п0148Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0031 {
            get {
                return this.п0031Field;
            }
            set {
                this.п0031Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0033 {
            get {
                return this.п0033Field;
            }
            set {
                this.п0033Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0425 {
            get {
                return this.п0425Field;
            }
            set {
                this.п0425Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0010 {
            get {
                return this.п0010Field;
            }
            set {
                this.п0010Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0975 {
            get {
                return this.п0975Field;
            }
            set {
                this.п0975Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0417 {
            get {
                return this.п0417Field;
            }
            set {
                this.п0417Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0419 {
            get {
                return this.п0419Field;
            }
            set {
                this.п0419Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0421 {
            get {
                return this.п0421Field;
            }
            set {
                this.п0421Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string П0430 {
            get {
                return this.п0430Field;
            }
            set {
                this.п0430Field = value;
            }
        }
    }
}
